<?php

namespace ContainerGmjEZxO;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9U6JZIcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9U6JZIc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'hmaServiceRepository' => ['privates', 'App\\Repository\\HmaServiceRepository', 'getHmaServiceRepositoryService', true],
            'subscriptionPlanRepository' => ['privates', 'App\\Repository\\SubscriptionPlanRepository', 'getSubscriptionPlanRepositoryService', true],
        ], [
            'entityManager' => '?',
            'hmaServiceRepository' => 'App\\Repository\\HmaServiceRepository',
            'subscriptionPlanRepository' => 'App\\Repository\\SubscriptionPlanRepository',
        ]);

        if (isset($container->privates['.service_locator.9U6JZIc'])) {
            return $container->privates['.service_locator.9U6JZIc'];
        }

        return $container->privates['.service_locator.9U6JZIc'] = $instance;
    }
}
