<?php

namespace ContainerGmjEZxO;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_X6B4nAgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.X6B4nAg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.X6B4nAg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'priceRepository' => ['services', 'App\\Repository\\AnalysisPriceRepository', 'getAnalysisPriceRepositoryService', true],
            'repository' => ['services', 'App\\Repository\\AnalysisRequestRepository', 'getAnalysisRequestRepositoryService', true],
        ], [
            'priceRepository' => 'App\\Repository\\AnalysisPriceRepository',
            'repository' => 'App\\Repository\\AnalysisRequestRepository',
        ]);
    }
}
