<?php

namespace ContainerGmjEZxO;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZigbG7gService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZigbG7g' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'promotionCategoryRecipe' => ['privates', '.errored..service_locator.ZigbG7g.App\\Entity\\PromotionCategoryRecipe', NULL, 'Cannot autowire service ".service_locator.ZigbG7g": it needs an instance of "App\\Entity\\PromotionCategoryRecipe" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'promotionCategoryRecipe' => 'App\\Entity\\PromotionCategoryRecipe',
        ]);

        if (isset($container->privates['.service_locator.ZigbG7g'])) {
            return $container->privates['.service_locator.ZigbG7g'];
        }

        return $container->privates['.service_locator.ZigbG7g'] = $instance;
    }
}
