<?php

namespace ContainerGmjEZxO;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SN8j6TcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sN8j6Tc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'purchaseItemRepository' => ['privates', 'App\\Repository\\PurchaseItemRepository', 'getPurchaseItemRepositoryService', true],
            'purchaseRepository' => ['privates', 'App\\Repository\\PurchaseRepository', 'getPurchaseRepositoryService', true],
            'service' => ['services', 'App\\Service\\SupplierCreditNoteService', 'getSupplierCreditNoteServiceService', true],
            'stockBatchRepository' => ['privates', 'App\\Repository\\StockBatchRepository', 'getStockBatchRepositoryService', true],
        ], [
            'purchaseItemRepository' => 'App\\Repository\\PurchaseItemRepository',
            'purchaseRepository' => 'App\\Repository\\PurchaseRepository',
            'service' => 'App\\Service\\SupplierCreditNoteService',
            'stockBatchRepository' => 'App\\Repository\\StockBatchRepository',
        ]);

        if (isset($container->privates['.service_locator.sN8j6Tc'])) {
            return $container->privates['.service_locator.sN8j6Tc'];
        }

        return $container->privates['.service_locator.sN8j6Tc'] = $instance;
    }
}
