<?php

namespace ContainerGmjEZxO;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Sy9ktqYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Sy9ktqY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Sy9ktqY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'inventory' => ['privates', '.errored..service_locator.Sy9ktqY.App\\Entity\\Inventory', NULL, 'Cannot autowire service ".service_locator.Sy9ktqY": it needs an instance of "App\\Entity\\Inventory" but this type has been excluded in "config/services.yaml".'],
        ], [
            'inventory' => 'App\\Entity\\Inventory',
        ]);
    }
}
