<?php

namespace ContainerGmjEZxO;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Msg5RWpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.msg5RWp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.msg5RWp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'transfer' => ['privates', '.errored..service_locator.msg5RWp.App\\Entity\\StockTransfer', NULL, 'Cannot autowire service ".service_locator.msg5RWp": it needs an instance of "App\\Entity\\StockTransfer" but this type has been excluded in "config/services.yaml".'],
        ], [
            'transfer' => 'App\\Entity\\StockTransfer',
        ]);
    }
}
