<?php

namespace ContainerGmjEZxO;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGenerateSalesReportCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\GenerateSalesReportCommand' shared autowired service.
     *
     * @return \App\Command\GenerateSalesReportCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'GenerateSalesReportCommand.php';

        $container->privates['App\\Command\\GenerateSalesReportCommand'] = $instance = new \App\Command\GenerateSalesReportCommand();

        $instance->setName('app:generate-sales-report');
        $instance->setDescription('Génère un rapport de ventes Excel (à implémenter)');

        return $instance;
    }
}
