<?php

namespace ContainerGmjEZxO;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPharmacyControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Marketplace\PharmacyController' shared autowired service.
     *
     * @return \App\Controller\Marketplace\PharmacyController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'Marketplace'.\DIRECTORY_SEPARATOR.'PharmacyController.php';

        $container->services['App\\Controller\\Marketplace\\PharmacyController'] = $instance = new \App\Controller\Marketplace\PharmacyController();

        $instance->setContainer(($container->privates['.service_locator.siKanuc'] ?? $container->load('get_ServiceLocator_SiKanucService'))->withContext('App\\Controller\\Marketplace\\PharmacyController', $container));

        return $instance;
    }
}
