<?php

namespace ContainerCGsOVkT;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EsReojiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EsReoji' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'type' => ['privates', '.errored..service_locator.EsReoji.App\\Entity\\TypePromotion', NULL, 'Cannot autowire service ".service_locator.EsReoji": it needs an instance of "App\\Entity\\TypePromotion" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'type' => 'App\\Entity\\TypePromotion',
        ]);

        if (isset($container->privates['.service_locator.EsReoji'])) {
            return $container->privates['.service_locator.EsReoji'];
        }

        return $container->privates['.service_locator.EsReoji'] = $instance;
    }
}
