<?php

namespace ContainerCGsOVkT;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KF6svHuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kF6svHu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kF6svHu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cartRepository' => ['services', 'App\\Repository\\CartRepository', 'getCartRepositoryService', false],
            'categoryRepository' => ['privates', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService', false],
            'favoriteRepository' => ['privates', 'App\\Repository\\FavoriteRepository', 'getFavoriteRepositoryService', false],
            'orderItemRepository' => ['privates', 'App\\Repository\\OrderItemRepository', 'getOrderItemRepositoryService', false],
            'productRepository' => ['privates', 'App\\Repository\\ProductRepository', 'getProductRepositoryService', true],
            'ratingRepository' => ['privates', 'App\\Repository\\RatingRepository', 'getRatingRepositoryService', true],
        ], [
            'cartRepository' => 'App\\Repository\\CartRepository',
            'categoryRepository' => 'App\\Repository\\CategoryRepository',
            'favoriteRepository' => 'App\\Repository\\FavoriteRepository',
            'orderItemRepository' => 'App\\Repository\\OrderItemRepository',
            'productRepository' => 'App\\Repository\\ProductRepository',
            'ratingRepository' => 'App\\Repository\\RatingRepository',
        ]);
    }
}
