<?php

namespace ContainerCGsOVkT;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProxyInitializerServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Service\ProxyInitializerService' shared autowired service.
     *
     * @return \App\Service\ProxyInitializerService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'ProxyInitializerService.php';

        return $container->services['App\\Service\\ProxyInitializerService'] = new \App\Service\ProxyInitializerService(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));
    }
}
