<?php

namespace ContainerCGsOVkT;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStockBatchService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.lIYMlB2.App\Entity\StockBatch' shared service.
     *
     * @return \App\Entity\StockBatch
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.lIYMlB2": it needs an instance of "App\\Entity\\StockBatch" but this type has been excluded in "config/services.yaml".');
    }
}
