<?php

namespace ContainerCkU4tre;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPromotionRecipe2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.WeDmv2U.App\Entity\PromotionRecipe' shared service.
     *
     * @return \App\Entity\PromotionRecipe
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.WeDmv2U": it needs an instance of "App\\Entity\\PromotionRecipe" but this type has been excluded in "config/services.yaml".');
    }
}
