<?php

namespace ContainerCkU4tre;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSubscription2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.aQv.1uC.App\Entity\Subscription' shared service.
     *
     * @return \App\Entity\Subscription
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.aQv.1uC": it needs an instance of "App\\Entity\\Subscription" but this type has been excluded in "config/services.yaml".');
    }
}
