<?php

namespace ContainerWxah5xV;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VHj21WxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vHj21Wx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vHj21Wx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cartService' => ['privates', 'App\\Service\\PurchaseCartService', 'getPurchaseCartServiceService', true],
        ], [
            'cartService' => 'App\\Service\\PurchaseCartService',
        ]);
    }
}
