<?php

namespace ContainerWxah5xV;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RZ0EafJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rZ0EafJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'purchase' => ['privates', '.errored..service_locator.rZ0EafJ.App\\Entity\\Purchase', NULL, 'Cannot autowire service ".service_locator.rZ0EafJ": it needs an instance of "App\\Entity\\Purchase" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'mailer' => '?',
            'purchase' => 'App\\Entity\\Purchase',
        ]);

        if (isset($container->privates['.service_locator.rZ0EafJ'])) {
            return $container->privates['.service_locator.rZ0EafJ'];
        }

        return $container->privates['.service_locator.rZ0EafJ'] = $instance;
    }
}
