<?php

namespace ContainerS44YR1e;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VJEETNRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VJEETNR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'category' => ['privates', '.errored..service_locator.VJEETNR.App\\Entity\\CategoryRecipe', NULL, 'Cannot autowire service ".service_locator.VJEETNR": it needs an instance of "App\\Entity\\CategoryRecipe" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'category' => 'App\\Entity\\CategoryRecipe',
            'entityManager' => '?',
        ]);

        if (isset($container->privates['.service_locator.VJEETNR'])) {
            return $container->privates['.service_locator.VJEETNR'];
        }

        return $container->privates['.service_locator.VJEETNR'] = $instance;
    }
}
