<?php

namespace ContainerS44YR1e;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSubscriptionControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\SubscriptionController' shared autowired service.
     *
     * @return \App\Controller\SubscriptionController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'SubscriptionController.php';

        $container->services['App\\Controller\\SubscriptionController'] = $instance = new \App\Controller\SubscriptionController(($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)), ($container->privates['App\\Service\\InvoicePdfGenerator'] ?? $container->load('getInvoicePdfGeneratorService')), ($container->privates['App\\Service\\QuotaEnforcementService'] ?? $container->load('getQuotaEnforcementServiceService')));

        $instance->setContainer(($container->privates['.service_locator.2ZRjhdO'] ?? $container->load('get_ServiceLocator_2ZRjhdOService'))->withContext('App\\Controller\\SubscriptionController', $container));

        return $instance;
    }
}
