framework:
    secret: '%env(APP_SECRET)%'

    serializer:
        enabled: true
    property_info:
        enabled: true
    
    # Désactiver CSRF au niveau framework
    csrf_protection:
        enabled: true
    
    # Configuration sessions (garder simple)
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        name: HMASESSID
    
    php_errors:
        log: true