<?php

namespace ContainerIxxwMdf;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Uzo7QTNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uzo7QTN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uzo7QTN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'recipe' => ['privates', '.errored..service_locator.uzo7QTN.App\\Entity\\Recipe', NULL, 'Cannot autowire service ".service_locator.uzo7QTN": it needs an instance of "App\\Entity\\Recipe" but this type has been excluded in "config/services.yaml".'],
        ], [
            'recipe' => 'App\\Entity\\Recipe',
        ]);
    }
}
