<?php

namespace ContainerIxxwMdf;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FM5yHseService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fM5yHse' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fM5yHse'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cartService' => ['privates', 'App\\Service\\PurchaseCartService', 'getPurchaseCartServiceService', true],
            'productRepository' => ['privates', 'App\\Repository\\ProductRepository', 'getProductRepositoryService', true],
        ], [
            'cartService' => 'App\\Service\\PurchaseCartService',
            'productRepository' => 'App\\Repository\\ProductRepository',
        ]);
    }
}
