<?php

namespace ContainerMpvmGH9;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnalysisRequestRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Repository\AnalysisRequestRepository' shared autowired service.
     *
     * @return \App\Repository\AnalysisRequestRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'AnalysisRequestRepository.php';

        return $container->services['App\\Repository\\AnalysisRequestRepository'] = new \App\Repository\AnalysisRequestRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
