<?php

namespace Container9eHZlhr;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ys0sGM_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ys0sGM.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ys0sGM.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'promotionProduct' => ['privates', '.errored..service_locator.Ys0sGM..App\\Entity\\PromotionProduct', NULL, 'Cannot autowire service ".service_locator.Ys0sGM.": it needs an instance of "App\\Entity\\PromotionProduct" but this type has been excluded in "config/services.yaml".'],
        ], [
            'promotionProduct' => 'App\\Entity\\PromotionProduct',
        ]);
    }
}
