<?php

namespace Container9eHZlhr;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TFDMK8MService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TFDMK8M' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TFDMK8M'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'orderRepository' => ['privates', 'App\\Repository\\OrderRepository', 'getOrderRepositoryService', true],
            'returnOrderRepository' => ['privates', 'App\\Repository\\ReturnOrderRepository', 'getReturnOrderRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'orderRepository' => 'App\\Repository\\OrderRepository',
            'returnOrderRepository' => 'App\\Repository\\ReturnOrderRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
