<?php

namespace ContainerF6HPx4x;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCheckExpiredSubscriptionsCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Command\CheckExpiredSubscriptionsCommand' shared autowired service.
     *
     * @return \App\Command\CheckExpiredSubscriptionsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\CheckExpiredSubscriptionsCommand'] = $instance = new \App\Command\CheckExpiredSubscriptionsCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Service\\QuotaEnforcementService'] ?? $container->load('getQuotaEnforcementServiceService')));

        $instance->setName('app:check-expired-subscriptions');
        $instance->setDescription('Vérifie les abonnements expirés et bascule en freemium.');

        return $instance;
    }
}
