<?php

namespace ContainerF6HPx4x;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCleanIncompleteCustomersCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Command\CleanIncompleteCustomersCommand' shared autowired service.
     *
     * @return \App\Command\CleanIncompleteCustomersCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\CleanIncompleteCustomersCommand'] = $instance = new \App\Command\CleanIncompleteCustomersCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('app:clean-incomplete-customers');
        $instance->setDescription('Nettoie les clients avec inscription incomplète (soft delete après 7 jours)');

        return $instance;
    }
}
