<?php

namespace ContainerF6HPx4x;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCheckPublicStatusCommand_LazyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.App\Command\CheckPublicStatusCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\Command\\CheckPublicStatusCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:check-public-status', [], 'Affiche le statut public de toutes les entreprises.', false, #[\Closure(name: 'App\\Command\\CheckPublicStatusCommand')] fn (): \App\Command\CheckPublicStatusCommand => ($container->privates['App\\Command\\CheckPublicStatusCommand'] ?? $container->load('getCheckPublicStatusCommandService')));
    }
}
