<?php

namespace ContainerF6HPx4x;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCleanIncompleteRegistrationsCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Command\CleanIncompleteRegistrationsCommand' shared autowired service.
     *
     * @return \App\Command\CleanIncompleteRegistrationsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\CleanIncompleteRegistrationsCommand'] = $instance = new \App\Command\CleanIncompleteRegistrationsCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('app:clean-incomplete-registrations');
        $instance->setDescription('Supprime les inscriptions incomplètes de plus de 24h (HmaService sans activation)');

        return $instance;
    }
}
