<?php

namespace ContainerF6HPx4x;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCleanIncompleteCustomersCommand_LazyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.App\Command\CleanIncompleteCustomersCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\Command\\CleanIncompleteCustomersCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:clean-incomplete-customers', [], 'Nettoie les clients avec inscription incomplète (soft delete après 7 jours)', false, #[\Closure(name: 'App\\Command\\CleanIncompleteCustomersCommand')] fn (): \App\Command\CleanIncompleteCustomersCommand => ($container->privates['App\\Command\\CleanIncompleteCustomersCommand'] ?? $container->load('getCleanIncompleteCustomersCommandService')));
    }
}
