<?php

namespace ContainerF6HPx4x;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCheckPublicStatusCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Command\CheckPublicStatusCommand' shared autowired service.
     *
     * @return \App\Command\CheckPublicStatusCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\CheckPublicStatusCommand'] = $instance = new \App\Command\CheckPublicStatusCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('app:check-public-status');
        $instance->setDescription('Affiche le statut public de toutes les entreprises.');

        return $instance;
    }
}
