<?php

namespace ContainerF6HPx4x;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChangePasswordControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Marketplace\ChangePasswordController' shared autowired service.
     *
     * @return \App\Controller\Marketplace\ChangePasswordController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Marketplace\\ChangePasswordController'] = $instance = new \App\Controller\Marketplace\ChangePasswordController();

        $instance->setContainer(($container->privates['.service_locator.siKanuc'] ?? $container->load('get_ServiceLocator_SiKanucService'))->withContext('App\\Controller\\Marketplace\\ChangePasswordController', $container));

        return $instance;
    }
}
