<?php

namespace ContainerF6HPx4x;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmployeeRoleCountRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\EmployeeRoleCountRepository' shared autowired service.
     *
     * @return \App\Repository\EmployeeRoleCountRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\EmployeeRoleCountRepository'] = new \App\Repository\EmployeeRoleCountRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
