<?php

namespace ContainerF6HPx4x;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEnforceQuotasCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Command\EnforceQuotasCommand' shared autowired service.
     *
     * @return \App\Command\EnforceQuotasCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\EnforceQuotasCommand'] = $instance = new \App\Command\EnforceQuotasCommand(($container->privates['App\\Service\\QuotaEnforcementService'] ?? $container->load('getQuotaEnforcementServiceService')));

        $instance->setName('app:enforce-quotas');
        $instance->setDescription('Applique les quotas actuels à toutes les entreprises (désactive/réactive les entités).');

        return $instance;
    }
}
