<?php

namespace ContainerF6HPx4x;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFinancialCalculatorServiceService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Service\Report\FinancialCalculatorService' shared autowired service.
     *
     * @return \App\Service\Report\FinancialCalculatorService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['App\\Service\\Report\\FinancialCalculatorService'] = new \App\Service\Report\FinancialCalculatorService(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\PaymentRepository'] ?? $container->load('getPaymentRepositoryService')), ($container->privates['App\\Repository\\SubscriptionRepository'] ?? $container->load('getSubscriptionRepositoryService')), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));
    }
}
