<?php

namespace ContainerF6HPx4x;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInventoryControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Stock\InventoryController' shared autowired service.
     *
     * @return \App\Controller\Stock\InventoryController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Stock\\InventoryController'] = $instance = new \App\Controller\Stock\InventoryController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->services['App\\Service\\Stock\\StockInventoryService'] ?? $container->load('getStockInventoryServiceService')));

        $instance->setContainer(($container->privates['.service_locator.siKanuc'] ?? $container->load('get_ServiceLocator_SiKanucService'))->withContext('App\\Controller\\Stock\\InventoryController', $container));

        return $instance;
    }
}
