<?php

namespace ContainerF6HPx4x;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLogoutListenerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\EventListener\LogoutListener' shared autowired service.
     *
     * @return \App\EventListener\LogoutListener
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\EventListener\\LogoutListener'])) {
            return $container->privates['App\\EventListener\\LogoutListener'];
        }

        $instance = new \App\EventListener\LogoutListener($a);

        if (isset($container->privates['App\\EventListener\\LogoutListener'])) {
            return $container->privates['App\\EventListener\\LogoutListener'];
        }

        return $container->privates['App\\EventListener\\LogoutListener'] = $instance;
    }
}
