<?php

namespace ContainerF6HPx4x;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotificationServiceService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Service\NotificationService' shared autowired service.
     *
     * @return \App\Service\NotificationService
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService'));

        if (isset($container->services['App\\Service\\NotificationService'])) {
            return $container->services['App\\Service\\NotificationService'];
        }
        $b = ($container->privates['twig'] ?? $container->load('getTwigService'));

        if (isset($container->services['App\\Service\\NotificationService'])) {
            return $container->services['App\\Service\\NotificationService'];
        }
        $c = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->services['App\\Service\\NotificationService'])) {
            return $container->services['App\\Service\\NotificationService'];
        }

        $instance = new \App\Service\NotificationService($a, $b, ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)), $container->getEnv('MAILER_FROM_EMAIL'), $container->getEnv('APP_URL'), false, $c);

        if (isset($container->services['App\\Service\\NotificationService'])) {
            return $container->services['App\\Service\\NotificationService'];
        }

        return $container->services['App\\Service\\NotificationService'] = $instance;
    }
}
