<?php

namespace ContainerF6HPx4x;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductSearchControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Api\ProductSearchController' shared autowired service.
     *
     * @return \App\Controller\Api\ProductSearchController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Api\\ProductSearchController'] = $instance = new \App\Controller\Api\ProductSearchController(($container->services['App\\Service\\ProductSearchService'] ?? $container->load('getProductSearchServiceService')));

        $instance->setContainer(($container->privates['.service_locator.siKanuc'] ?? $container->load('get_ServiceLocator_SiKanucService'))->withContext('App\\Controller\\Api\\ProductSearchController', $container));

        return $instance;
    }
}
