<?php

namespace ContainerF6HPx4x;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentController3Service extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\SuperAdmin\PaymentController' shared autowired service.
     *
     * @return \App\Controller\SuperAdmin\PaymentController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\SuperAdmin\\PaymentController'] = $instance = new \App\Controller\SuperAdmin\PaymentController();

        $instance->setContainer(($container->privates['.service_locator.siKanuc'] ?? $container->load('get_ServiceLocator_SiKanucService'))->withContext('App\\Controller\\SuperAdmin\\PaymentController', $container));

        return $instance;
    }
}
