<?php

namespace ContainerF6HPx4x;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPurchaseReceiptTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\PurchaseReceiptType' shared autowired service.
     *
     * @return \App\Form\PurchaseReceiptType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\PurchaseReceiptType'] = new \App\Form\PurchaseReceiptType();
    }
}
