<?php

namespace ContainerF6HPx4x;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Admin\ProductController' shared autowired service.
     *
     * @return \App\Controller\Admin\ProductController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Admin\\ProductController'] = $instance = new \App\Controller\Admin\ProductController(($container->privates['slugger'] ??= new \Symfony\Component\String\Slugger\AsciiSlugger('fr')), ($container->privates['App\\Service\\UnitConverter'] ??= new \App\Service\UnitConverter()), ($container->privates['App\\Service\\UniqueNameValidator'] ?? $container->load('getUniqueNameValidatorService')));

        $instance->setContainer(($container->privates['.service_locator.siKanuc'] ?? $container->load('get_ServiceLocator_SiKanucService'))->withContext('App\\Controller\\Admin\\ProductController', $container));

        return $instance;
    }
}
