<?php

namespace ContainerF6HPx4x;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQuotaManagerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\QuotaManager' shared autowired service.
     *
     * @return \App\Service\QuotaManager
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\QuotaManager'] = new \App\Service\QuotaManager(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)), ($container->services['App\\Service\\EmailService'] ?? $container->load('getEmailServiceService')));
    }
}
