<?php

namespace ContainerF6HPx4x;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReturnControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Return\ReturnController' shared autowired service.
     *
     * @return \App\Controller\Return\ReturnController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Return\\ReturnController'] = $instance = new \App\Controller\Return\ReturnController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->services['App\\Service\\Return\\ReturnService'] ?? $container->load('getReturnServiceService')), ($container->privates['App\\Repository\\ReturnOrderRepository'] ?? $container->load('getReturnOrderRepositoryService')), ($container->privates['App\\Repository\\OrderRepository'] ?? $container->load('getOrderRepositoryService')), ($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));

        $instance->setContainer(($container->privates['.service_locator.siKanuc'] ?? $container->load('get_ServiceLocator_SiKanucService'))->withContext('App\\Controller\\Return\\ReturnController', $container));

        return $instance;
    }
}
