<?php

namespace ContainerF6HPx4x;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSupplierCreditNoteRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\SupplierCreditNoteRepository' shared autowired service.
     *
     * @return \App\Repository\SupplierCreditNoteRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\SupplierCreditNoteRepository'] = new \App\Repository\SupplierCreditNoteRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
