<?php

namespace ContainerF6HPx4x;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSupplierControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Admin\SupplierController' shared autowired service.
     *
     * @return \App\Controller\Admin\SupplierController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Admin\\SupplierController'] = $instance = new \App\Controller\Admin\SupplierController();

        $instance->setContainer(($container->privates['.service_locator.siKanuc'] ?? $container->load('get_ServiceLocator_SiKanucService'))->withContext('App\\Controller\\Admin\\SupplierController', $container));

        return $instance;
    }
}
