<?php

namespace ContainerF6HPx4x;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSubscriptionController2Service extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\SubscriptionController' shared autowired service.
     *
     * @return \App\Controller\SubscriptionController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\SubscriptionController'] = $instance = new \App\Controller\SubscriptionController(($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)), ($container->privates['App\\Service\\InvoicePdfGenerator'] ?? $container->load('getInvoicePdfGeneratorService')), ($container->privates['App\\Service\\QuotaEnforcementService'] ?? $container->load('getQuotaEnforcementServiceService')));

        $instance->setContainer(($container->privates['.service_locator.siKanuc'] ?? $container->load('get_ServiceLocator_SiKanucService'))->withContext('App\\Controller\\SubscriptionController', $container));

        return $instance;
    }
}
