<?php

namespace ContainerF6HPx4x;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSaleExportServiceService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Service\Export\SaleExportService' shared autowired service.
     *
     * @return \App\Service\Export\SaleExportService
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->services['App\\Service\\Export\\SaleExportService'])) {
            return $container->services['App\\Service\\Export\\SaleExportService'];
        }
        $b = ($container->privates['security.helper'] ?? self::getSecurity_HelperService($container));

        if (isset($container->services['App\\Service\\Export\\SaleExportService'])) {
            return $container->services['App\\Service\\Export\\SaleExportService'];
        }
        $c = ($container->privates['twig'] ?? $container->load('getTwigService'));

        if (isset($container->services['App\\Service\\Export\\SaleExportService'])) {
            return $container->services['App\\Service\\Export\\SaleExportService'];
        }

        $instance = new \App\Service\Export\SaleExportService($a, ($container->privates['App\\Repository\\OrderRepository'] ?? $container->load('getOrderRepositoryService')), (\dirname(__DIR__, 4).'/public/uploads/exports/sales'), $b, $c);

        if (isset($container->services['App\\Service\\Export\\SaleExportService'])) {
            return $container->services['App\\Service\\Export\\SaleExportService'];
        }

        return $container->services['App\\Service\\Export\\SaleExportService'] = $instance;
    }
}
