<?php

namespace ContainerF6HPx4x;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStatisticsRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\StatisticsRepository' shared autowired service.
     *
     * @return \App\Repository\StatisticsRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['knp_paginator'] ?? $container->load('getKnpPaginatorService'));

        if (isset($container->privates['App\\Repository\\StatisticsRepository'])) {
            return $container->privates['App\\Repository\\StatisticsRepository'];
        }

        $instance = new \App\Repository\StatisticsRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)), $a);

        if (isset($container->privates['App\\Repository\\StatisticsRepository'])) {
            return $container->privates['App\\Repository\\StatisticsRepository'];
        }

        return $container->privates['App\\Repository\\StatisticsRepository'] = $instance;
    }
}
