<?php

namespace ContainerF6HPx4x;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSendExpirationRemindersCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Command\SendExpirationRemindersCommand' shared autowired service.
     *
     * @return \App\Command\SendExpirationRemindersCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\SendExpirationRemindersCommand'] = $instance = new \App\Command\SendExpirationRemindersCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->services['App\\Service\\EmailService'] ?? $container->load('getEmailServiceService')));

        $instance->setName('app:send-expiration-reminders');

        return $instance;
    }
}
