<?php

namespace ContainerF6HPx4x;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_User_Provider_Concrete_ChainProviderService extends App_KernelProdContainer
{
    /*
     * Gets the private 'security.user.provider.concrete.chain_provider' shared service.
     *
     * @return \Symfony\Component\Security\Core\User\ChainUserProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['security.user.provider.concrete.chain_provider'] = new \Symfony\Component\Security\Core\User\ChainUserProvider(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['security.user.provider.concrete.user_provider'] ?? $container->load('getSecurity_User_Provider_Concrete_UserProviderService'));
            yield 1 => ($container->privates['security.user.provider.concrete.hma_service_provider'] ?? $container->load('getSecurity_User_Provider_Concrete_HmaServiceProviderService'));
        }, 2));
    }
}
