<?php

namespace ContainerF6HPx4x;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStatisticsControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\SuperAdmin\StatisticsController' shared autowired service.
     *
     * @return \App\Controller\SuperAdmin\StatisticsController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\SuperAdmin\\StatisticsController'] = $instance = new \App\Controller\SuperAdmin\StatisticsController(($container->privates['App\\Repository\\StatisticsRepository'] ?? $container->load('getStatisticsRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.siKanuc'] ?? $container->load('get_ServiceLocator_SiKanucService'))->withContext('App\\Controller\\SuperAdmin\\StatisticsController', $container));

        return $instance;
    }
}
