<?php

namespace ContainerF6HPx4x;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestEmailCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Command\TestEmailCommand' shared autowired service.
     *
     * @return \App\Command\TestEmailCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\TestEmailCommand'] = $instance = new \App\Command\TestEmailCommand(($container->services['App\\Service\\EmailService'] ?? $container->load('getEmailServiceService')));

        $instance->setName('app:test-email');

        return $instance;
    }
}
