<?php

namespace ContainerF6HPx4x;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUnlockLockedUsersCommand_LazyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.App\Command\UnlockLockedUsersCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\Command\\UnlockLockedUsersCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:unlock-locked-users', [], 'Débloque tous les utilisateurs dont la période de blocage est expirée', false, #[\Closure(name: 'App\\Command\\UnlockLockedUsersCommand')] fn (): \App\Command\UnlockLockedUsersCommand => ($container->privates['App\\Command\\UnlockLockedUsersCommand'] ?? $container->load('getUnlockLockedUsersCommandService')));
    }
}
