<?php

namespace ContainerKDdyX5G;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KNDsrdSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KNDsrdS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KNDsrdS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'purchaseItem' => ['privates', '.errored..service_locator.KNDsrdS.App\\Entity\\PurchaseItem', NULL, 'Cannot autowire service ".service_locator.KNDsrdS": it needs an instance of "App\\Entity\\PurchaseItem" but this type has been excluded in "config/services.yaml".'],
        ], [
            'purchaseItem' => 'App\\Entity\\PurchaseItem',
        ]);
    }
}
