<?php

namespace ContainerZCTcUFw;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPurchaseControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Admin\PurchaseController' shared autowired service.
     *
     * @return \App\Controller\Admin\PurchaseController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'Admin'.\DIRECTORY_SEPARATOR.'PurchaseController.php';

        $container->services['App\\Controller\\Admin\\PurchaseController'] = $instance = new \App\Controller\Admin\PurchaseController(($container->services['kernel'] ?? $container->get('kernel', 1)));

        $instance->setContainer(($container->privates['.service_locator.fqNVFHW'] ?? $container->load('get_ServiceLocator_FqNVFHWService'))->withContext('App\\Controller\\Admin\\PurchaseController', $container));

        return $instance;
    }
}
