<?php

namespace ContainerN082Iap;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSubscriptionController2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\SuperAdmin\SubscriptionController' shared autowired service.
     *
     * @return \App\Controller\SuperAdmin\SubscriptionController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'SuperAdmin'.\DIRECTORY_SEPARATOR.'SubscriptionController.php';

        $container->services['App\\Controller\\SuperAdmin\\SubscriptionController'] = $instance = new \App\Controller\SuperAdmin\SubscriptionController();

        $instance->setContainer(($container->privates['.service_locator.WgYxIqT'] ?? $container->load('get_ServiceLocator_WgYxIqTService'))->withContext('App\\Controller\\SuperAdmin\\SubscriptionController', $container));

        return $instance;
    }
}
