<?php

namespace ContainerRvSdsq3;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeactivateExpiredBatchesCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\DeactivateExpiredBatchesCommand' shared autowired service.
     *
     * @return \App\Command\DeactivateExpiredBatchesCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'DeactivateExpiredBatchesCommand.php';

        $container->privates['App\\Command\\DeactivateExpiredBatchesCommand'] = $instance = new \App\Command\DeactivateExpiredBatchesCommand(($container->services['App\\Service\\Sale\\StockDeductionService'] ?? $container->load('getStockDeductionServiceService')));

        $instance->setName('app:batches:deactivate-expired');

        return $instance;
    }
}
