<?php

namespace ContainerMfAJ2T2;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NeEnakrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NeEnakr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NeEnakr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'company' => ['privates', '.errored..service_locator.NeEnakr.App\\Entity\\HmaService', NULL, 'Cannot autowire service ".service_locator.NeEnakr": it needs an instance of "App\\Entity\\HmaService" but this type has been excluded in "config/services.yaml".'],
            'repository' => ['services', 'App\\Repository\\AnalysisRequestRepository', 'getAnalysisRequestRepositoryService', true],
        ], [
            'company' => 'App\\Entity\\HmaService',
            'repository' => 'App\\Repository\\AnalysisRequestRepository',
        ]);
    }
}
