<?php

namespace ContainerMfAJ2T2;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Xld5WjMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Xld5WjM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'analysisRequest' => ['privates', '.errored..service_locator.Xld5WjM.App\\Entity\\AnalysisRequest', NULL, 'Cannot autowire service ".service_locator.Xld5WjM": it needs an instance of "App\\Entity\\AnalysisRequest" but this type has been excluded in "config/services.yaml".'],
            'exportService' => ['services', 'App\\Service\\SuperAdmin\\CompanyAnalysisExportService', 'getCompanyAnalysisExportServiceService', true],
        ], [
            'analysisRequest' => 'App\\Entity\\AnalysisRequest',
            'exportService' => 'App\\Service\\SuperAdmin\\CompanyAnalysisExportService',
        ]);

        if (isset($container->privates['.service_locator.Xld5WjM'])) {
            return $container->privates['.service_locator.Xld5WjM'];
        }

        return $container->privates['.service_locator.Xld5WjM'] = $instance;
    }
}
