<?php

namespace ContainerMfAJ2T2;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NW1L6AbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NW1L6Ab' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NW1L6Ab'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'companyRepository' => ['privates', 'App\\Repository\\HmaServiceRepository', 'getHmaServiceRepositoryService', true],
            'priceRepository' => ['services', 'App\\Repository\\AnalysisPriceRepository', 'getAnalysisPriceRepositoryService', true],
            'requestRepository' => ['services', 'App\\Repository\\AnalysisRequestRepository', 'getAnalysisRequestRepositoryService', true],
        ], [
            'companyRepository' => 'App\\Repository\\HmaServiceRepository',
            'priceRepository' => 'App\\Repository\\AnalysisPriceRepository',
            'requestRepository' => 'App\\Repository\\AnalysisRequestRepository',
        ]);
    }
}
