<?php

namespace ContainerMfAJ2T2;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCheckPublicStatusCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\CheckPublicStatusCommand' shared autowired service.
     *
     * @return \App\Command\CheckPublicStatusCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'CheckPublicStatusCommand.php';

        $container->privates['App\\Command\\CheckPublicStatusCommand'] = $instance = new \App\Command\CheckPublicStatusCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('app:check-public-status');
        $instance->setDescription('Affiche le statut public de toutes les entreprises.');

        return $instance;
    }
}
