<?php

namespace ContainerMfAJ2T2;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoryRecipeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.VJEETNR.App\Entity\CategoryRecipe' shared service.
     *
     * @return \App\Entity\CategoryRecipe
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.VJEETNR": it needs an instance of "App\\Entity\\CategoryRecipe" but this type has been excluded in "config/services.yaml".');
    }
}
