<?php

namespace ContainerMfAJ2T2;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getForm_RegistryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'form.registry' shared service.
     *
     * @return \Symfony\Component\Form\FormRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'FormRegistryInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'FormRegistry.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'FormExtensionInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'Extension'.\DIRECTORY_SEPARATOR.'DependencyInjection'.\DIRECTORY_SEPARATOR.'DependencyInjectionExtension.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'ResolvedFormTypeFactoryInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'Extension'.\DIRECTORY_SEPARATOR.'DataCollector'.\DIRECTORY_SEPARATOR.'Proxy'.\DIRECTORY_SEPARATOR.'ResolvedTypeFactoryDataCollectorProxy.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'ResolvedFormTypeFactory.php';

        return $container->privates['form.registry'] = new \Symfony\Component\Form\FormRegistry([new \Symfony\Component\Form\Extension\DependencyInjection\DependencyInjectionExtension(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Form\\AnalysisPriceType' => ['privates', 'App\\Form\\AnalysisPriceType', 'getAnalysisPriceTypeService', true],
            'App\\Form\\AnalysisRequestType' => ['privates', 'App\\Form\\AnalysisRequestType', 'getAnalysisRequestTypeService', true],
            'App\\Form\\CartItemType' => ['privates', 'App\\Form\\CartItemType', 'getCartItemTypeService', true],
            'App\\Form\\CategoryRecipeType' => ['privates', 'App\\Form\\CategoryRecipeType', 'getCategoryRecipeTypeService', true],
            'App\\Form\\CategoryType' => ['privates', 'App\\Form\\CategoryType', 'getCategoryTypeService', true],
            'App\\Form\\ChangePasswordFormType' => ['privates', 'App\\Form\\ChangePasswordFormType', 'getChangePasswordFormTypeService', true],
            'App\\Form\\CompanySettingsType' => ['privates', 'App\\Form\\CompanySettingsType', 'getCompanySettingsTypeService', true],
            'App\\Form\\CustomerChangePasswordType' => ['privates', 'App\\Form\\CustomerChangePasswordType', 'getCustomerChangePasswordTypeService', true],
            'App\\Form\\CustomerProfileType' => ['privates', 'App\\Form\\CustomerProfileType', 'getCustomerProfileTypeService', true],
            'App\\Form\\CustomerRegistrationType' => ['privates', 'App\\Form\\CustomerRegistrationType', 'getCustomerRegistrationTypeService', true],
            'App\\Form\\CustomerResetPasswordChangeFormType' => ['privates', 'App\\Form\\CustomerResetPasswordChangeFormType', 'getCustomerResetPasswordChangeFormTypeService', true],
            'App\\Form\\CustomerResetPasswordEmailType' => ['privates', 'App\\Form\\CustomerResetPasswordEmailType', 'getCustomerResetPasswordEmailTypeService', true],
            'App\\Form\\CustomerResetPasswordRequestFormType' => ['privates', 'App\\Form\\CustomerResetPasswordRequestFormType', 'getCustomerResetPasswordRequestFormTypeService', true],
            'App\\Form\\FirstLoginChangePasswordFormType' => ['privates', 'App\\Form\\FirstLoginChangePasswordFormType', 'getFirstLoginChangePasswordFormTypeService', true],
            'App\\Form\\FirstLoginChangePasswordType' => ['privates', 'App\\Form\\FirstLoginChangePasswordType', 'getFirstLoginChangePasswordTypeService', true],
            'App\\Form\\HmaServiceProfileType' => ['privates', 'App\\Form\\HmaServiceProfileType', 'getHmaServiceProfileTypeService', true],
            'App\\Form\\HmaServiceRegistrationType' => ['privates', 'App\\Form\\HmaServiceRegistrationType', 'getHmaServiceRegistrationTypeService', true],
            'App\\Form\\HmaServiceType' => ['privates', 'App\\Form\\HmaServiceType', 'getHmaServiceTypeService', true],
            'App\\Form\\LocationType' => ['privates', 'App\\Form\\LocationType', 'getLocationTypeService', true],
            'App\\Form\\ProductAutocompleteType' => ['privates', 'App\\Form\\ProductAutocompleteType', 'getProductAutocompleteTypeService', true],
            'App\\Form\\ProductType' => ['privates', 'App\\Form\\ProductType', 'getProductTypeService', true],
            'App\\Form\\ProfileType' => ['privates', 'App\\Form\\ProfileType', 'getProfileTypeService', true],
            'App\\Form\\PromotionCategoryRecipeType' => ['privates', 'App\\Form\\PromotionCategoryRecipeType', 'getPromotionCategoryRecipeTypeService', true],
            'App\\Form\\PromotionCategoryType' => ['privates', 'App\\Form\\PromotionCategoryType', 'getPromotionCategoryTypeService', true],
            'App\\Form\\PromotionProductType' => ['privates', 'App\\Form\\PromotionProductType', 'getPromotionProductTypeService', true],
            'App\\Form\\PromotionRecipeType' => ['privates', 'App\\Form\\PromotionRecipeType', 'getPromotionRecipeTypeService', true],
            'App\\Form\\PromotionType' => ['privates', 'App\\Form\\PromotionType', 'getPromotionTypeService', true],
            'App\\Form\\PurchaseConfirmationType' => ['privates', 'App\\Form\\PurchaseConfirmationType', 'getPurchaseConfirmationTypeService', true],
            'App\\Form\\PurchaseItemReceiptType' => ['privates', 'App\\Form\\PurchaseItemReceiptType', 'getPurchaseItemReceiptTypeService', true],
            'App\\Form\\PurchaseItemType' => ['privates', 'App\\Form\\PurchaseItemType', 'getPurchaseItemTypeService', true],
            'App\\Form\\PurchaseReceiptType' => ['privates', 'App\\Form\\PurchaseReceiptType', 'getPurchaseReceiptTypeService', true],
            'App\\Form\\PurchaseType' => ['privates', 'App\\Form\\PurchaseType', 'getPurchaseTypeService', true],
            'App\\Form\\ReceivePurchaseType' => ['privates', 'App\\Form\\ReceivePurchaseType', 'getReceivePurchaseTypeService', true],
            'App\\Form\\RecipeItemType' => ['privates', 'App\\Form\\RecipeItemType', 'getRecipeItemTypeService', true],
            'App\\Form\\RecipeType' => ['privates', 'App\\Form\\RecipeType', 'getRecipeTypeService', true],
            'App\\Form\\RegistrationFormType' => ['privates', 'App\\Form\\RegistrationFormType', 'getRegistrationFormTypeService', true],
            'App\\Form\\ResetPasswordChangeFormType' => ['privates', 'App\\Form\\ResetPasswordChangeFormType', 'getResetPasswordChangeFormTypeService', true],
            'App\\Form\\ResetPasswordRequestFormType' => ['privates', 'App\\Form\\ResetPasswordRequestFormType', 'getResetPasswordRequestFormTypeService', true],
            'App\\Form\\StockBatchEditType' => ['privates', 'App\\Form\\StockBatchEditType', 'getStockBatchEditTypeService', true],
            'App\\Form\\StockBatchType' => ['privates', 'App\\Form\\StockBatchType', 'getStockBatchTypeService', true],
            'App\\Form\\Stock\\InventoryAddProductsType' => ['privates', 'App\\Form\\Stock\\InventoryAddProductsType', 'getInventoryAddProductsTypeService', true],
            'App\\Form\\Stock\\InventoryType' => ['privates', 'App\\Form\\Stock\\InventoryType', 'getInventoryTypeService', true],
            'App\\Form\\Stock\\StockAdjustmentType' => ['privates', 'App\\Form\\Stock\\StockAdjustmentType', 'getStockAdjustmentTypeService', true],
            'App\\Form\\Stock\\StockTransferType' => ['privates', 'App\\Form\\Stock\\StockTransferType', 'getStockTransferTypeService', true],
            'App\\Form\\SubscriptionPlanType' => ['privates', 'App\\Form\\SubscriptionPlanType', 'getSubscriptionPlanTypeService', true],
            'App\\Form\\SubscriptionType' => ['privates', 'App\\Form\\SubscriptionType', 'getSubscriptionTypeService', true],
            'App\\Form\\SupplierCreditNoteType' => ['privates', 'App\\Form\\SupplierCreditNoteType', 'getSupplierCreditNoteTypeService', true],
            'App\\Form\\SupplierType' => ['privates', 'App\\Form\\SupplierType', 'getSupplierTypeService', true],
            'App\\Form\\TypePromotionType' => ['privates', 'App\\Form\\TypePromotionType', 'getTypePromotionTypeService', true],
            'App\\Form\\Type\\CountryType' => ['privates', 'App\\Form\\Type\\CountryType', 'getCountryTypeService', true],
            'App\\Form\\UserType' => ['privates', 'App\\Form\\UserType', 'getUserTypeService', true],
            'Symfony\\Bridge\\Doctrine\\Form\\Type\\EntityType' => ['privates', 'form.type.entity', 'getForm_Type_EntityService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType' => ['privates', 'form.type.choice', 'getForm_Type_ChoiceService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ColorType' => ['privates', 'form.type.color', 'getForm_Type_ColorService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FileType' => ['privates', 'form.type.file', 'getForm_Type_FileService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => ['privates', 'form.type.form', 'getForm_Type_FormService', true],
        ], [
            'App\\Form\\AnalysisPriceType' => '?',
            'App\\Form\\AnalysisRequestType' => '?',
            'App\\Form\\CartItemType' => '?',
            'App\\Form\\CategoryRecipeType' => '?',
            'App\\Form\\CategoryType' => '?',
            'App\\Form\\ChangePasswordFormType' => '?',
            'App\\Form\\CompanySettingsType' => '?',
            'App\\Form\\CustomerChangePasswordType' => '?',
            'App\\Form\\CustomerProfileType' => '?',
            'App\\Form\\CustomerRegistrationType' => '?',
            'App\\Form\\CustomerResetPasswordChangeFormType' => '?',
            'App\\Form\\CustomerResetPasswordEmailType' => '?',
            'App\\Form\\CustomerResetPasswordRequestFormType' => '?',
            'App\\Form\\FirstLoginChangePasswordFormType' => '?',
            'App\\Form\\FirstLoginChangePasswordType' => '?',
            'App\\Form\\HmaServiceProfileType' => '?',
            'App\\Form\\HmaServiceRegistrationType' => '?',
            'App\\Form\\HmaServiceType' => '?',
            'App\\Form\\LocationType' => '?',
            'App\\Form\\ProductAutocompleteType' => '?',
            'App\\Form\\ProductType' => '?',
            'App\\Form\\ProfileType' => '?',
            'App\\Form\\PromotionCategoryRecipeType' => '?',
            'App\\Form\\PromotionCategoryType' => '?',
            'App\\Form\\PromotionProductType' => '?',
            'App\\Form\\PromotionRecipeType' => '?',
            'App\\Form\\PromotionType' => '?',
            'App\\Form\\PurchaseConfirmationType' => '?',
            'App\\Form\\PurchaseItemReceiptType' => '?',
            'App\\Form\\PurchaseItemType' => '?',
            'App\\Form\\PurchaseReceiptType' => '?',
            'App\\Form\\PurchaseType' => '?',
            'App\\Form\\ReceivePurchaseType' => '?',
            'App\\Form\\RecipeItemType' => '?',
            'App\\Form\\RecipeType' => '?',
            'App\\Form\\RegistrationFormType' => '?',
            'App\\Form\\ResetPasswordChangeFormType' => '?',
            'App\\Form\\ResetPasswordRequestFormType' => '?',
            'App\\Form\\StockBatchEditType' => '?',
            'App\\Form\\StockBatchType' => '?',
            'App\\Form\\Stock\\InventoryAddProductsType' => '?',
            'App\\Form\\Stock\\InventoryType' => '?',
            'App\\Form\\Stock\\StockAdjustmentType' => '?',
            'App\\Form\\Stock\\StockTransferType' => '?',
            'App\\Form\\SubscriptionPlanType' => '?',
            'App\\Form\\SubscriptionType' => '?',
            'App\\Form\\SupplierCreditNoteType' => '?',
            'App\\Form\\SupplierType' => '?',
            'App\\Form\\TypePromotionType' => '?',
            'App\\Form\\Type\\CountryType' => '?',
            'App\\Form\\UserType' => '?',
            'Symfony\\Bridge\\Doctrine\\Form\\Type\\EntityType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ColorType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FileType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => '?',
        ]), ['Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_extension.form.transformation_failure_handling'] ?? $container->load('getForm_TypeExtension_Form_TransformationFailureHandlingService'));
            yield 1 => ($container->privates['form.type_extension.form.http_foundation'] ?? $container->load('getForm_TypeExtension_Form_HttpFoundationService'));
            yield 2 => ($container->privates['form.type_extension.form.validator'] ?? $container->load('getForm_TypeExtension_Form_ValidatorService'));
            yield 3 => ($container->privates['form.type_extension.upload.validator'] ?? $container->load('getForm_TypeExtension_Upload_ValidatorService'));
            yield 4 => ($container->privates['form.type_extension.csrf'] ?? $container->load('getForm_TypeExtension_CsrfService'));
            yield 5 => ($container->privates['form.type_extension.form.data_collector'] ?? $container->load('getForm_TypeExtension_Form_DataCollectorService'));
            yield 6 => ($container->privates['form.type_extension.form.password_hasher'] ?? $container->load('getForm_TypeExtension_Form_PasswordHasherService'));
        }, 7), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\RepeatedType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_extension.repeated.validator'] ??= new \Symfony\Component\Form\Extension\Validator\Type\RepeatedTypeValidatorExtension());
        }, 1), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\SubmitType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_extension.submit.validator'] ??= new \Symfony\Component\Form\Extension\Validator\Type\SubmitTypeValidatorExtension());
        }, 1), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\PasswordType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_extension.password.password_hasher'] ?? $container->load('getForm_TypeExtension_Password_PasswordHasherService'));
        }, 1)], new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_guesser.validator'] ?? $container->load('getForm_TypeGuesser_ValidatorService'));
            yield 1 => ($container->privates['form.type_guesser.doctrine'] ?? $container->load('getForm_TypeGuesser_DoctrineService'));
        }, 2))], new \Symfony\Component\Form\Extension\DataCollector\Proxy\ResolvedTypeFactoryDataCollectorProxy(new \Symfony\Component\Form\ResolvedFormTypeFactory(), ($container->privates['data_collector.form'] ?? self::getDataCollector_FormService($container))));
    }
}
