<?php

namespace ContainerMfAJ2T2;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPurchaseItemService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.KNDsrdS.App\Entity\PurchaseItem' shared service.
     *
     * @return \App\Entity\PurchaseItem
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.KNDsrdS": it needs an instance of "App\\Entity\\PurchaseItem" but this type has been excluded in "config/services.yaml".');
    }
}
