<?php

namespace Container0xVyor1;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Dn2OtwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._dn2Otw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._dn2Otw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repository' => ['privates', 'App\\Repository\\StockTransferRepository', 'getStockTransferRepositoryService', true],
        ], [
            'repository' => 'App\\Repository\\StockTransferRepository',
        ]);
    }
}
