<?php

namespace Container0xVyor1;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPurchaseControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\PurchaseController' shared autowired service.
     *
     * @return \App\Controller\PurchaseController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'PurchaseController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'PurchaseFlowService.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));
        $b = ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container));
        $c = ($container->privates['App\\Service\\InvoicePdfGenerator'] ?? $container->load('getInvoicePdfGeneratorService'));

        $container->services['App\\Controller\\PurchaseController'] = $instance = new \App\Controller\PurchaseController($a, new \App\Service\PurchaseFlowService($a, ($container->services['App\\Service\\NotificationService'] ?? $container->load('getNotificationServiceService')), ($container->services['App\\Service\\StockService'] ?? $container->load('getStockServiceService')), $b, ($container->privates['security.helper'] ?? self::getSecurity_HelperService($container)), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), (\dirname(__DIR__, 4).'/public/uploads/bons-commande'), (\dirname(__DIR__, 4).'/public/uploads/recus-achat'), $c), $b, $c);

        $instance->setContainer(($container->privates['.service_locator.siKanuc'] ?? $container->load('get_ServiceLocator_SiKanucService'))->withContext('App\\Controller\\PurchaseController', $container));

        return $instance;
    }
}
