<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerF6HPx4x\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerF6HPx4x/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerF6HPx4x.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerF6HPx4x\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerF6HPx4x\App_KernelProdContainer([
    'container.build_hash' => 'F6HPx4x',
    'container.build_id' => '1b2e8156',
    'container.build_time' => 1782672592,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerF6HPx4x');
