<?php

namespace ContainerAMERzft;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ktyp3kRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ktyp3kR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'fileUploader' => ['privates', 'App\\Service\\FileUploader', 'getFileUploaderService', true],
            'hmaService' => ['privates', '.errored..service_locator.ktyp3kR.App\\Entity\\HmaService', NULL, 'Cannot autowire service ".service_locator.ktyp3kR": it needs an instance of "App\\Entity\\HmaService" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'fileUploader' => 'App\\Service\\FileUploader',
            'hmaService' => 'App\\Entity\\HmaService',
        ]);

        if (isset($container->privates['.service_locator.ktyp3kR'])) {
            return $container->privates['.service_locator.ktyp3kR'];
        }

        return $container->privates['.service_locator.ktyp3kR'] = $instance;
    }
}
