<?php

namespace ContainerAMERzft;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCleanIncompleteRegistrationsCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\CleanIncompleteRegistrationsCommand' shared autowired service.
     *
     * @return \App\Command\CleanIncompleteRegistrationsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'CleanIncompleteRegistrationsCommand.php';

        $container->privates['App\\Command\\CleanIncompleteRegistrationsCommand'] = $instance = new \App\Command\CleanIncompleteRegistrationsCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('app:clean-incomplete-registrations');
        $instance->setDescription('Supprime les inscriptions incomplètes de plus de 24h (HmaService sans activation)');

        return $instance;
    }
}
