<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class SupplierCreditNote extends \App\Entity\SupplierCreditNote implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'affected_quantity' => [parent::class, 'affected_quantity', null, 16],
        "\0".parent::class."\0".'attachments' => [parent::class, 'attachments', null, 16],
        "\0".parent::class."\0".'created_at' => [parent::class, 'created_at', null, 16],
        "\0".parent::class."\0".'credit_note_number' => [parent::class, 'credit_note_number', null, 16],
        "\0".parent::class."\0".'declared_amount' => [parent::class, 'declared_amount', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'histories' => [parent::class, 'histories', null, 16],
        "\0".parent::class."\0".'hma_service' => [parent::class, 'hma_service', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'internal_notes' => [parent::class, 'internal_notes', null, 16],
        "\0".parent::class."\0".'issue_type' => [parent::class, 'issue_type', null, 16],
        "\0".parent::class."\0".'lost_amount' => [parent::class, 'lost_amount', null, 16],
        "\0".parent::class."\0".'priority' => [parent::class, 'priority', null, 16],
        "\0".parent::class."\0".'purchase' => [parent::class, 'purchase', null, 16],
        "\0".parent::class."\0".'recovered_amount' => [parent::class, 'recovered_amount', null, 16],
        "\0".parent::class."\0".'reported_at' => [parent::class, 'reported_at', null, 16],
        "\0".parent::class."\0".'reported_by' => [parent::class, 'reported_by', null, 16],
        "\0".parent::class."\0".'resolution_notes' => [parent::class, 'resolution_notes', null, 16],
        "\0".parent::class."\0".'resolved_at' => [parent::class, 'resolved_at', null, 16],
        "\0".parent::class."\0".'resolved_by' => [parent::class, 'resolved_by', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'stockBatch' => [parent::class, 'stockBatch', null, 16],
        "\0".parent::class."\0".'stock_action' => [parent::class, 'stock_action', null, 16],
        "\0".parent::class."\0".'stock_action_applied' => [parent::class, 'stock_action_applied', null, 16],
        "\0".parent::class."\0".'supplier' => [parent::class, 'supplier', null, 16],
        "\0".parent::class."\0".'supplier_decision' => [parent::class, 'supplier_decision', null, 16],
        "\0".parent::class."\0".'supplier_proposed_amount' => [parent::class, 'supplier_proposed_amount', null, 16],
        "\0".parent::class."\0".'supplier_reference' => [parent::class, 'supplier_reference', null, 16],
        "\0".parent::class."\0".'supplier_response' => [parent::class, 'supplier_response', null, 16],
        "\0".parent::class."\0".'supplier_response_at' => [parent::class, 'supplier_response_at', null, 16],
        "\0".parent::class."\0".'updated_at' => [parent::class, 'updated_at', null, 16],
        'affected_quantity' => [parent::class, 'affected_quantity', null, 16],
        'attachments' => [parent::class, 'attachments', null, 16],
        'created_at' => [parent::class, 'created_at', null, 16],
        'credit_note_number' => [parent::class, 'credit_note_number', null, 16],
        'declared_amount' => [parent::class, 'declared_amount', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'histories' => [parent::class, 'histories', null, 16],
        'hma_service' => [parent::class, 'hma_service', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'internal_notes' => [parent::class, 'internal_notes', null, 16],
        'issue_type' => [parent::class, 'issue_type', null, 16],
        'lost_amount' => [parent::class, 'lost_amount', null, 16],
        'priority' => [parent::class, 'priority', null, 16],
        'purchase' => [parent::class, 'purchase', null, 16],
        'recovered_amount' => [parent::class, 'recovered_amount', null, 16],
        'reported_at' => [parent::class, 'reported_at', null, 16],
        'reported_by' => [parent::class, 'reported_by', null, 16],
        'resolution_notes' => [parent::class, 'resolution_notes', null, 16],
        'resolved_at' => [parent::class, 'resolved_at', null, 16],
        'resolved_by' => [parent::class, 'resolved_by', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'stockBatch' => [parent::class, 'stockBatch', null, 16],
        'stock_action' => [parent::class, 'stock_action', null, 16],
        'stock_action_applied' => [parent::class, 'stock_action_applied', null, 16],
        'supplier' => [parent::class, 'supplier', null, 16],
        'supplier_decision' => [parent::class, 'supplier_decision', null, 16],
        'supplier_proposed_amount' => [parent::class, 'supplier_proposed_amount', null, 16],
        'supplier_reference' => [parent::class, 'supplier_reference', null, 16],
        'supplier_response' => [parent::class, 'supplier_response', null, 16],
        'supplier_response_at' => [parent::class, 'supplier_response_at', null, 16],
        'updated_at' => [parent::class, 'updated_at', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
