<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'categories' => [parent::class, 'categories', null, 16],
        "\0".parent::class."\0".'created_at' => [parent::class, 'created_at', null, 16],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null, 16],
        "\0".parent::class."\0".'employment_date' => [parent::class, 'employment_date', null, 16],
        "\0".parent::class."\0".'full_name' => [parent::class, 'full_name', null, 16],
        "\0".parent::class."\0".'hma_service_id' => [parent::class, 'hma_service_id', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'is_active' => [parent::class, 'is_active', null, 16],
        "\0".parent::class."\0".'is_hma_owner' => [parent::class, 'is_hma_owner', null, 16],
        "\0".parent::class."\0".'is_super_admin' => [parent::class, 'is_super_admin', null, 16],
        "\0".parent::class."\0".'last_activity' => [parent::class, 'last_activity', null, 16],
        "\0".parent::class."\0".'login_at' => [parent::class, 'login_at', null, 16],
        "\0".parent::class."\0".'logout_at' => [parent::class, 'logout_at', null, 16],
        "\0".parent::class."\0".'orders' => [parent::class, 'orders', null, 16],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null, 16],
        "\0".parent::class."\0".'passwordChanged' => [parent::class, 'passwordChanged', null, 16],
        "\0".parent::class."\0".'phone' => [parent::class, 'phone', null, 16],
        "\0".parent::class."\0".'photo' => [parent::class, 'photo', null, 16],
        "\0".parent::class."\0".'products' => [parent::class, 'products', null, 16],
        "\0".parent::class."\0".'purchases' => [parent::class, 'purchases', null, 16],
        "\0".parent::class."\0".'roles' => [parent::class, 'roles', null, 16],
        "\0".parent::class."\0".'stockMovements' => [parent::class, 'stockMovements', null, 16],
        "\0".parent::class."\0".'subscription_active' => [parent::class, 'subscription_active', null, 16],
        "\0".parent::class."\0".'updated_at' => [parent::class, 'updated_at', null, 16],
        'categories' => [parent::class, 'categories', null, 16],
        'created_at' => [parent::class, 'created_at', null, 16],
        'email' => [parent::class, 'email', null, 16],
        'employment_date' => [parent::class, 'employment_date', null, 16],
        'full_name' => [parent::class, 'full_name', null, 16],
        'hma_service_id' => [parent::class, 'hma_service_id', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'is_active' => [parent::class, 'is_active', null, 16],
        'is_hma_owner' => [parent::class, 'is_hma_owner', null, 16],
        'is_super_admin' => [parent::class, 'is_super_admin', null, 16],
        'last_activity' => [parent::class, 'last_activity', null, 16],
        'login_at' => [parent::class, 'login_at', null, 16],
        'logout_at' => [parent::class, 'logout_at', null, 16],
        'orders' => [parent::class, 'orders', null, 16],
        'password' => [parent::class, 'password', null, 16],
        'passwordChanged' => [parent::class, 'passwordChanged', null, 16],
        'phone' => [parent::class, 'phone', null, 16],
        'photo' => [parent::class, 'photo', null, 16],
        'products' => [parent::class, 'products', null, 16],
        'purchases' => [parent::class, 'purchases', null, 16],
        'roles' => [parent::class, 'roles', null, 16],
        'stockMovements' => [parent::class, 'stockMovements', null, 16],
        'subscription_active' => [parent::class, 'subscription_active', null, 16],
        'updated_at' => [parent::class, 'updated_at', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
