<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Product extends \App\Entity\Product implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'barcode' => [parent::class, 'barcode', null, 16],
        "\0".parent::class."\0".'category' => [parent::class, 'category', null, 16],
        "\0".parent::class."\0".'created_at' => [parent::class, 'created_at', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'dosage' => [parent::class, 'dosage', null, 16],
        "\0".parent::class."\0".'form' => [parent::class, 'form', null, 16],
        "\0".parent::class."\0".'has_expiry_date' => [parent::class, 'has_expiry_date', null, 16],
        "\0".parent::class."\0".'hma_service' => [parent::class, 'hma_service', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'image' => [parent::class, 'image', null, 16],
        "\0".parent::class."\0".'is_active' => [parent::class, 'is_active', null, 16],
        "\0".parent::class."\0".'min_quantity' => [parent::class, 'min_quantity', null, 16],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null, 16],
        "\0".parent::class."\0".'prescription_required' => [parent::class, 'prescription_required', null, 16],
        "\0".parent::class."\0".'promotionProducts' => [parent::class, 'promotionProducts', null, 16],
        "\0".parent::class."\0".'purchaseItems' => [parent::class, 'purchaseItems', null, 16],
        "\0".parent::class."\0".'purchase_price' => [parent::class, 'purchase_price', null, 16],
        "\0".parent::class."\0".'sale_price' => [parent::class, 'sale_price', null, 16],
        "\0".parent::class."\0".'slug' => [parent::class, 'slug', null, 16],
        "\0".parent::class."\0".'stockBatches' => [parent::class, 'stockBatches', null, 16],
        "\0".parent::class."\0".'stockMovements' => [parent::class, 'stockMovements', null, 16],
        "\0".parent::class."\0".'stock_quantity' => [parent::class, 'stock_quantity', null, 16],
        "\0".parent::class."\0".'subscription_active' => [parent::class, 'subscription_active', null, 16],
        "\0".parent::class."\0".'unit' => [parent::class, 'unit', null, 16],
        "\0".parent::class."\0".'updated_at' => [parent::class, 'updated_at', null, 16],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null, 16],
        'barcode' => [parent::class, 'barcode', null, 16],
        'category' => [parent::class, 'category', null, 16],
        'created_at' => [parent::class, 'created_at', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'dosage' => [parent::class, 'dosage', null, 16],
        'form' => [parent::class, 'form', null, 16],
        'has_expiry_date' => [parent::class, 'has_expiry_date', null, 16],
        'hma_service' => [parent::class, 'hma_service', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'image' => [parent::class, 'image', null, 16],
        'is_active' => [parent::class, 'is_active', null, 16],
        'min_quantity' => [parent::class, 'min_quantity', null, 16],
        'name' => [parent::class, 'name', null, 16],
        'prescription_required' => [parent::class, 'prescription_required', null, 16],
        'promotionProducts' => [parent::class, 'promotionProducts', null, 16],
        'purchaseItems' => [parent::class, 'purchaseItems', null, 16],
        'purchase_price' => [parent::class, 'purchase_price', null, 16],
        'sale_price' => [parent::class, 'sale_price', null, 16],
        'slug' => [parent::class, 'slug', null, 16],
        'stockBatches' => [parent::class, 'stockBatches', null, 16],
        'stockMovements' => [parent::class, 'stockMovements', null, 16],
        'stock_quantity' => [parent::class, 'stock_quantity', null, 16],
        'subscription_active' => [parent::class, 'subscription_active', null, 16],
        'unit' => [parent::class, 'unit', null, 16],
        'updated_at' => [parent::class, 'updated_at', null, 16],
        'user' => [parent::class, 'user', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
