<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class OrderItem extends \App\Entity\OrderItem implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'batch_purchase_price' => [parent::class, 'batch_purchase_price', null, 16],
        "\0".parent::class."\0".'created_at' => [parent::class, 'created_at', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'originalUnitPrice' => [parent::class, 'originalUnitPrice', null, 16],
        "\0".parent::class."\0".'product_id' => [parent::class, 'product_id', null, 16],
        "\0".parent::class."\0".'product_name' => [parent::class, 'product_name', null, 16],
        "\0".parent::class."\0".'promotionDiscountAmount' => [parent::class, 'promotionDiscountAmount', null, 16],
        "\0".parent::class."\0".'promotionDiscountPercentage' => [parent::class, 'promotionDiscountPercentage', null, 16],
        "\0".parent::class."\0".'promotionId' => [parent::class, 'promotionId', null, 16],
        "\0".parent::class."\0".'promotionName' => [parent::class, 'promotionName', null, 16],
        "\0".parent::class."\0".'quantity' => [parent::class, 'quantity', null, 16],
        "\0".parent::class."\0".'recipe' => [parent::class, 'recipe', null, 16],
        "\0".parent::class."\0".'stock_batch_id' => [parent::class, 'stock_batch_id', null, 16],
        "\0".parent::class."\0".'total_price' => [parent::class, 'total_price', null, 16],
        "\0".parent::class."\0".'unit_price' => [parent::class, 'unit_price', null, 16],
        "\0".parent::class."\0".'vente' => [parent::class, 'vente', null, 16],
        'batch_purchase_price' => [parent::class, 'batch_purchase_price', null, 16],
        'created_at' => [parent::class, 'created_at', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'originalUnitPrice' => [parent::class, 'originalUnitPrice', null, 16],
        'product_id' => [parent::class, 'product_id', null, 16],
        'product_name' => [parent::class, 'product_name', null, 16],
        'promotionDiscountAmount' => [parent::class, 'promotionDiscountAmount', null, 16],
        'promotionDiscountPercentage' => [parent::class, 'promotionDiscountPercentage', null, 16],
        'promotionId' => [parent::class, 'promotionId', null, 16],
        'promotionName' => [parent::class, 'promotionName', null, 16],
        'quantity' => [parent::class, 'quantity', null, 16],
        'recipe' => [parent::class, 'recipe', null, 16],
        'stock_batch_id' => [parent::class, 'stock_batch_id', null, 16],
        'total_price' => [parent::class, 'total_price', null, 16],
        'unit_price' => [parent::class, 'unit_price', null, 16],
        'vente' => [parent::class, 'vente', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
