<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class HmaService extends \App\Entity\HmaService implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'activatedAt' => [parent::class, 'activatedAt', null, 16],
        "\0".parent::class."\0".'address' => [parent::class, 'address', null, 16],
        "\0".parent::class."\0".'categories' => [parent::class, 'categories', null, 16],
        "\0".parent::class."\0".'categoryCount' => [parent::class, 'categoryCount', null, 16],
        "\0".parent::class."\0".'city' => [parent::class, 'city', null, 16],
        "\0".parent::class."\0".'companyName' => [parent::class, 'companyName', null, 16],
        "\0".parent::class."\0".'companyType' => [parent::class, 'companyType', null, 16],
        "\0".parent::class."\0".'country' => [parent::class, 'country', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'dailyUsages' => [parent::class, 'dailyUsages', null, 16],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null, 16],
        "\0".parent::class."\0".'employeeRoleCounts' => [parent::class, 'employeeRoleCounts', null, 16],
        "\0".parent::class."\0".'hma_active' => [parent::class, 'hma_active', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'invoices' => [parent::class, 'invoices', null, 16],
        "\0".parent::class."\0".'isActive' => [parent::class, 'isActive', null, 16],
        "\0".parent::class."\0".'latitude' => [parent::class, 'latitude', null, 16],
        "\0".parent::class."\0".'logo' => [parent::class, 'logo', null, 16],
        "\0".parent::class."\0".'longitude' => [parent::class, 'longitude', null, 16],
        "\0".parent::class."\0".'orderCount' => [parent::class, 'orderCount', null, 16],
        "\0".parent::class."\0".'orders' => [parent::class, 'orders', null, 16],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null, 16],
        "\0".parent::class."\0".'payments' => [parent::class, 'payments', null, 16],
        "\0".parent::class."\0".'phone' => [parent::class, 'phone', null, 16],
        "\0".parent::class."\0".'productCount' => [parent::class, 'productCount', null, 16],
        "\0".parent::class."\0".'products' => [parent::class, 'products', null, 16],
        "\0".parent::class."\0".'purchases' => [parent::class, 'purchases', null, 16],
        "\0".parent::class."\0".'stockBatches' => [parent::class, 'stockBatches', null, 16],
        "\0".parent::class."\0".'stockMovements' => [parent::class, 'stockMovements', null, 16],
        "\0".parent::class."\0".'subscriptionEndsAt' => [parent::class, 'subscriptionEndsAt', null, 16],
        "\0".parent::class."\0".'subscriptionPlan' => [parent::class, 'subscriptionPlan', null, 16],
        "\0".parent::class."\0".'subscriptionStartAt' => [parent::class, 'subscriptionStartAt', null, 16],
        "\0".parent::class."\0".'subscription_number' => [parent::class, 'subscription_number', null, 16],
        "\0".parent::class."\0".'subscriptions' => [parent::class, 'subscriptions', null, 16],
        "\0".parent::class."\0".'supplierCount' => [parent::class, 'supplierCount', null, 16],
        "\0".parent::class."\0".'suppliers' => [parent::class, 'suppliers', null, 16],
        "\0".parent::class."\0".'trialEndsAt' => [parent::class, 'trialEndsAt', null, 16],
        "\0".parent::class."\0".'updated_at' => [parent::class, 'updated_at', null, 16],
        "\0".parent::class."\0".'userCount' => [parent::class, 'userCount', null, 16],
        "\0".parent::class."\0".'users' => [parent::class, 'users', null, 16],
        'activatedAt' => [parent::class, 'activatedAt', null, 16],
        'address' => [parent::class, 'address', null, 16],
        'categories' => [parent::class, 'categories', null, 16],
        'categoryCount' => [parent::class, 'categoryCount', null, 16],
        'city' => [parent::class, 'city', null, 16],
        'companyName' => [parent::class, 'companyName', null, 16],
        'companyType' => [parent::class, 'companyType', null, 16],
        'country' => [parent::class, 'country', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'dailyUsages' => [parent::class, 'dailyUsages', null, 16],
        'email' => [parent::class, 'email', null, 16],
        'employeeRoleCounts' => [parent::class, 'employeeRoleCounts', null, 16],
        'hma_active' => [parent::class, 'hma_active', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'invoices' => [parent::class, 'invoices', null, 16],
        'isActive' => [parent::class, 'isActive', null, 16],
        'latitude' => [parent::class, 'latitude', null, 16],
        'logo' => [parent::class, 'logo', null, 16],
        'longitude' => [parent::class, 'longitude', null, 16],
        'orderCount' => [parent::class, 'orderCount', null, 16],
        'orders' => [parent::class, 'orders', null, 16],
        'password' => [parent::class, 'password', null, 16],
        'payments' => [parent::class, 'payments', null, 16],
        'phone' => [parent::class, 'phone', null, 16],
        'productCount' => [parent::class, 'productCount', null, 16],
        'products' => [parent::class, 'products', null, 16],
        'purchases' => [parent::class, 'purchases', null, 16],
        'stockBatches' => [parent::class, 'stockBatches', null, 16],
        'stockMovements' => [parent::class, 'stockMovements', null, 16],
        'subscriptionEndsAt' => [parent::class, 'subscriptionEndsAt', null, 16],
        'subscriptionPlan' => [parent::class, 'subscriptionPlan', null, 16],
        'subscriptionStartAt' => [parent::class, 'subscriptionStartAt', null, 16],
        'subscription_number' => [parent::class, 'subscription_number', null, 16],
        'subscriptions' => [parent::class, 'subscriptions', null, 16],
        'supplierCount' => [parent::class, 'supplierCount', null, 16],
        'suppliers' => [parent::class, 'suppliers', null, 16],
        'trialEndsAt' => [parent::class, 'trialEndsAt', null, 16],
        'updated_at' => [parent::class, 'updated_at', null, 16],
        'userCount' => [parent::class, 'userCount', null, 16],
        'users' => [parent::class, 'users', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
