<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Purchase extends \App\Entity\Purchase implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'bon_commande' => [parent::class, 'bon_commande', null, 16],
        "\0".parent::class."\0".'cancellation_reason' => [parent::class, 'cancellation_reason', null, 16],
        "\0".parent::class."\0".'cancelled_at' => [parent::class, 'cancelled_at', null, 16],
        "\0".parent::class."\0".'cancelled_by' => [parent::class, 'cancelled_by', null, 16],
        "\0".parent::class."\0".'confirmed_at' => [parent::class, 'confirmed_at', null, 16],
        "\0".parent::class."\0".'created_at' => [parent::class, 'created_at', null, 16],
        "\0".parent::class."\0".'hma_service' => [parent::class, 'hma_service', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'notes' => [parent::class, 'notes', null, 16],
        "\0".parent::class."\0".'purchaseItems' => [parent::class, 'purchaseItems', null, 16],
        "\0".parent::class."\0".'purchase_number' => [parent::class, 'purchase_number', null, 16],
        "\0".parent::class."\0".'received_at' => [parent::class, 'received_at', null, 16],
        "\0".parent::class."\0".'recu_achat' => [parent::class, 'recu_achat', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'supplier' => [parent::class, 'supplier', null, 16],
        "\0".parent::class."\0".'total_amount' => [parent::class, 'total_amount', null, 16],
        "\0".parent::class."\0".'updated_at' => [parent::class, 'updated_at', null, 16],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null, 16],
        'bon_commande' => [parent::class, 'bon_commande', null, 16],
        'cancellation_reason' => [parent::class, 'cancellation_reason', null, 16],
        'cancelled_at' => [parent::class, 'cancelled_at', null, 16],
        'cancelled_by' => [parent::class, 'cancelled_by', null, 16],
        'confirmed_at' => [parent::class, 'confirmed_at', null, 16],
        'created_at' => [parent::class, 'created_at', null, 16],
        'hma_service' => [parent::class, 'hma_service', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'notes' => [parent::class, 'notes', null, 16],
        'purchaseItems' => [parent::class, 'purchaseItems', null, 16],
        'purchase_number' => [parent::class, 'purchase_number', null, 16],
        'received_at' => [parent::class, 'received_at', null, 16],
        'recu_achat' => [parent::class, 'recu_achat', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'supplier' => [parent::class, 'supplier', null, 16],
        'total_amount' => [parent::class, 'total_amount', null, 16],
        'updated_at' => [parent::class, 'updated_at', null, 16],
        'user' => [parent::class, 'user', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
