<?php

namespace Container655ZU0i;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GCnJrcbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GCnJrcb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'location' => ['privates', '.errored..service_locator.GCnJrcb.App\\Entity\\Location', NULL, 'Cannot autowire service ".service_locator.GCnJrcb": it needs an instance of "App\\Entity\\Location" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'location' => 'App\\Entity\\Location',
        ]);

        if (isset($container->privates['.service_locator.GCnJrcb'])) {
            return $container->privates['.service_locator.GCnJrcb'];
        }

        return $container->privates['.service_locator.GCnJrcb'] = $instance;
    }
}
