<?php

namespace Container655ZU0i;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInventoryRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\InventoryRepository' shared autowired service.
     *
     * @return \App\Repository\InventoryRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'InventoryRepository.php';

        return $container->privates['App\\Repository\\InventoryRepository'] = new \App\Repository\InventoryRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
