<?php

namespace ContainerVzUnxBb;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPurchase4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.nnTODkK.App\Entity\Purchase' shared service.
     *
     * @return \App\Entity\Purchase
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.nnTODkK": it needs an instance of "App\\Entity\\Purchase" but this type has been excluded in "config/services.yaml".');
    }
}
