<?php

namespace ContainerVzUnxBb;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSubscriptionPaymentServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Service\Payment\SubscriptionPaymentService' shared autowired service.
     *
     * @return \App\Service\Payment\SubscriptionPaymentService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Payment'.\DIRECTORY_SEPARATOR.'SubscriptionPaymentService.php';

        return $container->services['App\\Service\\Payment\\SubscriptionPaymentService'] = new \App\Service\Payment\SubscriptionPaymentService(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Service\\FedaPayService'] ?? $container->load('getFedaPayServiceService')), ($container->services['App\\Service\\NotificationService'] ?? $container->load('getNotificationServiceService')), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));
    }
}
