<?php

namespace ContainerSRJyzxF;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EpX10X9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.epX10X9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'batchRepository' => ['privates', 'App\\Repository\\StockBatchRepository', 'getStockBatchRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'location' => ['privates', '.errored..service_locator.epX10X9.App\\Entity\\Location', NULL, 'Cannot autowire service ".service_locator.epX10X9": it needs an instance of "App\\Entity\\Location" but this type has been excluded in "config/services.yaml".'],
            'locationRepository' => ['privates', 'App\\Repository\\LocationRepository', 'getLocationRepositoryService', true],
        ], [
            'batchRepository' => 'App\\Repository\\StockBatchRepository',
            'em' => '?',
            'location' => 'App\\Entity\\Location',
            'locationRepository' => 'App\\Repository\\LocationRepository',
        ]);

        if (isset($container->privates['.service_locator.epX10X9'])) {
            return $container->privates['.service_locator.epX10X9'];
        }

        return $container->privates['.service_locator.epX10X9'] = $instance;
    }
}
