<?php

namespace ContainerSRJyzxF;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSendSubscriptionRemindersCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\SendSubscriptionRemindersCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'LazyCommand.php';

        return $container->privates['.App\\Command\\SendSubscriptionRemindersCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:send-subscription-reminders', [], 'Envoie des rappels pour les abonnements sur le point d\'expirer', false, #[\Closure(name: 'App\\Command\\SendSubscriptionRemindersCommand')] fn (): \App\Command\SendSubscriptionRemindersCommand => ($container->privates['App\\Command\\SendSubscriptionRemindersCommand'] ?? $container->load('getSendSubscriptionRemindersCommandService')));
    }
}
