<?php

namespace ContainerWJIAC95;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NEOlKDhService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NEOlKDh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NEOlKDh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'subscription' => ['privates', '.errored..service_locator.NEOlKDh.App\\Entity\\Subscription', NULL, 'Cannot autowire service ".service_locator.NEOlKDh": it needs an instance of "App\\Entity\\Subscription" but this type has been excluded in "config/services.yaml".'],
        ], [
            'subscription' => 'App\\Entity\\Subscription',
        ]);
    }
}
