<?php

namespace ContainerWJIAC95;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRestaurantSaleControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Sale\RestaurantSaleController' shared autowired service.
     *
     * @return \App\Controller\Sale\RestaurantSaleController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'Sale'.\DIRECTORY_SEPARATOR.'BaseSaleController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'Sale'.\DIRECTORY_SEPARATOR.'RestaurantSaleController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'UnitConverter.php';

        $container->services['App\\Controller\\Sale\\RestaurantSaleController'] = $instance = new \App\Controller\Sale\RestaurantSaleController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->services['App\\Service\\Sale\\SaleService'] ?? $container->load('getSaleServiceService')), ($container->services['App\\Service\\Sale\\PromotionCalculator'] ?? $container->load('getPromotionCalculatorService')), ($container->privates['App\\Service\\UnitConverter'] ??= new \App\Service\UnitConverter()));

        $instance->setContainer(($container->privates['.service_locator.siKanuc'] ?? $container->load('get_ServiceLocator_SiKanucService'))->withContext('App\\Controller\\Sale\\RestaurantSaleController', $container));

        return $instance;
    }
}
