<?php

namespace ContainerBjJ9qxX;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WP3ZJtService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wP3Z_Jt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wP3Z_Jt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'analysisRequest' => ['privates', '.errored..service_locator.wP3Z_Jt.App\\Entity\\AnalysisRequest', NULL, 'Cannot autowire service ".service_locator.wP3Z_Jt": it needs an instance of "App\\Entity\\AnalysisRequest" but this type has been excluded in "config/services.yaml".'],
            'fedaPayService' => ['privates', 'App\\Service\\FedaPayService', 'getFedaPayServiceService', true],
        ], [
            'analysisRequest' => 'App\\Entity\\AnalysisRequest',
            'fedaPayService' => 'App\\Service\\FedaPayService',
        ]);
    }
}
