<?php

namespace ContainerBjJ9qxX;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStockAdjustmentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.eDr0rba.App\Entity\StockAdjustment' shared service.
     *
     * @return \App\Entity\StockAdjustment
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.eDr0rba": it needs an instance of "App\\Entity\\StockAdjustment" but this type has been excluded in "config/services.yaml".');
    }
}
