<?php

namespace ContainerBjJ9qxX;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTypePromotion2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.zIb6dGh.App\Entity\TypePromotion' shared service.
     *
     * @return \App\Entity\TypePromotion
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.zIb6dGh": it needs an instance of "App\\Entity\\TypePromotion" but this type has been excluded in "config/services.yaml".');
    }
}
