<?php

namespace ContainerWyCti1W;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GQbEjC7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gQbEjC7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'exportService' => ['services', 'App\\Service\\Export\\SaleExportService', 'getSaleExportServiceService', true],
            'orderRepository' => ['privates', 'App\\Repository\\OrderRepository', 'getOrderRepositoryService', true],
        ], [
            'exportService' => 'App\\Service\\Export\\SaleExportService',
            'orderRepository' => 'App\\Repository\\OrderRepository',
        ]);

        if (isset($container->privates['.service_locator.gQbEjC7'])) {
            return $container->privates['.service_locator.gQbEjC7'];
        }

        return $container->privates['.service_locator.gQbEjC7'] = $instance;
    }
}
