<?php

namespace ContainerWyCti1W;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCleanIncompleteRegistrationsCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\CleanIncompleteRegistrationsCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'LazyCommand.php';

        return $container->privates['.App\\Command\\CleanIncompleteRegistrationsCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:clean-incomplete-registrations', [], 'Supprime les inscriptions incomplètes de plus de 24h (HmaService sans activation)', false, #[\Closure(name: 'App\\Command\\CleanIncompleteRegistrationsCommand')] fn (): \App\Command\CleanIncompleteRegistrationsCommand => ($container->privates['App\\Command\\CleanIncompleteRegistrationsCommand'] ?? $container->load('getCleanIncompleteRegistrationsCommandService')));
    }
}
