<?php

namespace ContainerWyCti1W;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPromotionRecipeRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\PromotionRecipeRepository' shared autowired service.
     *
     * @return \App\Repository\PromotionRecipeRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'PromotionRecipeRepository.php';

        return $container->privates['App\\Repository\\PromotionRecipeRepository'] = new \App\Repository\PromotionRecipeRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
