<?php

namespace ContainerWyCti1W;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUnlockLockedUsersCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\UnlockLockedUsersCommand' shared autowired service.
     *
     * @return \App\Command\UnlockLockedUsersCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'UnlockLockedUsersCommand.php';

        $container->privates['App\\Command\\UnlockLockedUsersCommand'] = $instance = new \App\Command\UnlockLockedUsersCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('app:unlock-locked-users');
        $instance->setDescription('Débloque tous les utilisateurs dont la période de blocage est expirée');

        return $instance;
    }
}
