<?php

namespace ContainerQ4znEHR;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PZ9vOm3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pZ9vOm3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'emailService' => ['services', 'App\\Service\\EmailService', 'getEmailServiceService', true],
            'fedaPay' => ['privates', 'App\\Service\\FedaPayService', 'getFedaPayServiceService', true],
        ], [
            'em' => '?',
            'emailService' => 'App\\Service\\EmailService',
            'fedaPay' => 'App\\Service\\FedaPayService',
        ]);

        if (isset($container->privates['.service_locator.pZ9vOm3'])) {
            return $container->privates['.service_locator.pZ9vOm3'];
        }

        return $container->privates['.service_locator.pZ9vOm3'] = $instance;
    }
}
