<?php

namespace ContainerQ4znEHR;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCleanExpiredAnalysisCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\CleanExpiredAnalysisCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'LazyCommand.php';

        return $container->privates['.App\\Command\\CleanExpiredAnalysisCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:clean-expired-analysis', [], 'Nettoie les demandes d\'analyse expirées', false, #[\Closure(name: 'App\\Command\\CleanExpiredAnalysisCommand')] fn (): \App\Command\CleanExpiredAnalysisCommand => ($container->privates['App\\Command\\CleanExpiredAnalysisCommand'] ?? $container->load('getCleanExpiredAnalysisCommandService')));
    }
}
