<?php

namespace ContainerQ4znEHR;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInvoiceRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\InvoiceRepository' shared autowired service.
     *
     * @return \App\Repository\InvoiceRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'InvoiceRepository.php';

        return $container->privates['App\\Repository\\InvoiceRepository'] = new \App\Repository\InvoiceRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
