<?php

namespace ContainerXJbt02a;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZVX5_KUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zVX5.kU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'batchRepository' => ['privates', 'App\\Repository\\StockBatchRepository', 'getStockBatchRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'batchRepository' => 'App\\Repository\\StockBatchRepository',
            'em' => '?',
        ]);

        if (isset($container->privates['.service_locator.zVX5.kU'])) {
            return $container->privates['.service_locator.zVX5.kU'];
        }

        return $container->privates['.service_locator.zVX5.kU'] = $instance;
    }
}
