<?php

namespace ContainerXJbt02a;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPromotionProduct2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Ys0sGM..App\Entity\PromotionProduct' shared service.
     *
     * @return \App\Entity\PromotionProduct
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Ys0sGM.": it needs an instance of "App\\Entity\\PromotionProduct" but this type has been excluded in "config/services.yaml".');
    }
}
