<?php

namespace ContainerUxCB6On;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DC4Tbs0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dC4Tbs0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'purchase' => ['privates', '.errored..service_locator.dC4Tbs0.App\\Entity\\Purchase', NULL, 'Cannot autowire service ".service_locator.dC4Tbs0": it needs an instance of "App\\Entity\\Purchase" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'purchase' => 'App\\Entity\\Purchase',
        ]);

        if (isset($container->privates['.service_locator.dC4Tbs0'])) {
            return $container->privates['.service_locator.dC4Tbs0'];
        }

        return $container->privates['.service_locator.dC4Tbs0'] = $instance;
    }
}
