<?php

namespace ContainerUxCB6On;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ArpVjFCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.arpVjFC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.arpVjFC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'locationRepository' => ['privates', 'App\\Repository\\LocationRepository', 'getLocationRepositoryService', true],
            'purchase' => ['privates', '.errored..service_locator.arpVjFC.App\\Entity\\Purchase', NULL, 'Cannot autowire service ".service_locator.arpVjFC": it needs an instance of "App\\Entity\\Purchase" but this type has been excluded in "config/services.yaml".'],
        ], [
            'locationRepository' => 'App\\Repository\\LocationRepository',
            'purchase' => 'App\\Entity\\Purchase',
        ]);
    }
}
