<?php

namespace ContainerGxmO4Pd;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RC6pteXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rC6pteX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rC6pteX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'promotionCategory' => ['privates', '.errored..service_locator.rC6pteX.App\\Entity\\PromotionCategory', NULL, 'Cannot autowire service ".service_locator.rC6pteX": it needs an instance of "App\\Entity\\PromotionCategory" but this type has been excluded in "config/services.yaml".'],
        ], [
            'promotionCategory' => 'App\\Entity\\PromotionCategory',
        ]);
    }
}
