<?php

namespace ContainerGxmO4Pd;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_U6cEktGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.u6cEktG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.u6cEktG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'company' => ['privates', '.errored..service_locator.u6cEktG.App\\Entity\\HmaService', NULL, 'Cannot autowire service ".service_locator.u6cEktG": it needs an instance of "App\\Entity\\HmaService" but this type has been excluded in "config/services.yaml".'],
            'paymentRepository' => ['privates', 'App\\Repository\\PaymentRepository', 'getPaymentRepositoryService', true],
            'subscriptionRepository' => ['privates', 'App\\Repository\\SubscriptionRepository', 'getSubscriptionRepositoryService', false],
        ], [
            'company' => 'App\\Entity\\HmaService',
            'paymentRepository' => 'App\\Repository\\PaymentRepository',
            'subscriptionRepository' => 'App\\Repository\\SubscriptionRepository',
        ]);
    }
}
