<?php

namespace ContainerGxmO4Pd;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnalysisRequest4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.wP3Z_Jt.App\Entity\AnalysisRequest' shared service.
     *
     * @return \App\Entity\AnalysisRequest
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.wP3Z_Jt": it needs an instance of "App\\Entity\\AnalysisRequest" but this type has been excluded in "config/services.yaml".');
    }
}
