<?php

namespace ContainerGxmO4Pd;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCheckExpiredSubscriptionsCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\CheckExpiredSubscriptionsCommand' shared autowired service.
     *
     * @return \App\Command\CheckExpiredSubscriptionsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'CheckExpiredSubscriptionsCommand.php';

        $container->privates['App\\Command\\CheckExpiredSubscriptionsCommand'] = $instance = new \App\Command\CheckExpiredSubscriptionsCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Service\\QuotaEnforcementService'] ?? $container->load('getQuotaEnforcementServiceService')));

        $instance->setName('app:check-expired-subscriptions');
        $instance->setDescription('Vérifie les abonnements expirés et bascule en freemium.');

        return $instance;
    }
}
