<?php

namespace ContainerGxmO4Pd;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEnforceQuotasCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\EnforceQuotasCommand' shared autowired service.
     *
     * @return \App\Command\EnforceQuotasCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'EnforceQuotasCommand.php';

        $container->privates['App\\Command\\EnforceQuotasCommand'] = $instance = new \App\Command\EnforceQuotasCommand(($container->privates['App\\Service\\QuotaEnforcementService'] ?? $container->load('getQuotaEnforcementServiceService')));

        $instance->setName('app:enforce-quotas');
        $instance->setDescription('Applique les quotas actuels à toutes les entreprises (désactive/réactive les entités).');

        return $instance;
    }
}
