<?php

namespace ContainerGxmO4Pd;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFinancialCalculatorServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Service\Report\FinancialCalculatorService' shared autowired service.
     *
     * @return \App\Service\Report\FinancialCalculatorService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Report'.\DIRECTORY_SEPARATOR.'FinancialCalculatorService.php';

        return $container->services['App\\Service\\Report\\FinancialCalculatorService'] = new \App\Service\Report\FinancialCalculatorService(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\PaymentRepository'] ?? $container->load('getPaymentRepositoryService')), ($container->privates['App\\Repository\\SubscriptionRepository'] ?? self::getSubscriptionRepositoryService($container)), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));
    }
}
