<?php

namespace ContainerGxmO4Pd;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReceiptGeneratorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Service\Sale\ReceiptGenerator' shared autowired service.
     *
     * @return \App\Service\Sale\ReceiptGenerator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Sale'.\DIRECTORY_SEPARATOR.'ReceiptGenerator.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'dompdf'.\DIRECTORY_SEPARATOR.'dompdf'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Dompdf.php';

        return $container->services['App\\Service\\Sale\\ReceiptGenerator'] = new \App\Service\Sale\ReceiptGenerator(($container->privates['twig'] ?? self::getTwigService($container)), new \Dompdf\Dompdf(), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)), (\dirname(__DIR__, 4).'/public/uploads/receipts'));
    }
}
