<?php

namespace ContainerGxmO4Pd;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStatisticsRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\StatisticsRepository' shared autowired service.
     *
     * @return \App\Repository\StatisticsRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'StatisticsRepository.php';

        $a = ($container->services['knp_paginator'] ?? $container->load('getKnpPaginatorService'));

        if (isset($container->privates['App\\Repository\\StatisticsRepository'])) {
            return $container->privates['App\\Repository\\StatisticsRepository'];
        }

        $instance = new \App\Repository\StatisticsRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)), $a);

        if (isset($container->privates['App\\Repository\\StatisticsRepository'])) {
            return $container->privates['App\\Repository\\StatisticsRepository'];
        }

        return $container->privates['App\\Repository\\StatisticsRepository'] = $instance;
    }
}
