<?php

namespace ContainerK13AwMn;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EVrFYPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._EVrFYP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._EVrFYP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'paymentRepository' => ['privates', 'App\\Repository\\PaymentRepository', 'getPaymentRepositoryService', true],
            'subscription' => ['privates', '.errored..service_locator._EVrFYP.App\\Entity\\Subscription', NULL, 'Cannot autowire service ".service_locator._EVrFYP": it needs an instance of "App\\Entity\\Subscription" but this type has been excluded in "config/services.yaml".'],
        ], [
            'paymentRepository' => 'App\\Repository\\PaymentRepository',
            'subscription' => 'App\\Entity\\Subscription',
        ]);
    }
}
