<?php

namespace ContainerK13AwMn;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSupplierCreditNote2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.sKSeD8o.App\Entity\SupplierCreditNote' shared service.
     *
     * @return \App\Entity\SupplierCreditNote
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.sKSeD8o": it needs an instance of "App\\Entity\\SupplierCreditNote" but this type has been excluded in "config/services.yaml".');
    }
}
