<?php

namespace ContainerE5XgzCF;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LEubkBDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lEubkBD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'analysisRequest' => ['privates', '.errored..service_locator.lEubkBD.App\\Entity\\AnalysisRequest', NULL, 'Cannot autowire service ".service_locator.lEubkBD": it needs an instance of "App\\Entity\\AnalysisRequest" but this type has been excluded in "config/services.yaml".'],
            'notificationService' => ['services', 'App\\Service\\NotificationService', 'getNotificationServiceService', true],
        ], [
            'analysisRequest' => 'App\\Entity\\AnalysisRequest',
            'notificationService' => 'App\\Service\\NotificationService',
        ]);

        if (isset($container->privates['.service_locator.lEubkBD'])) {
            return $container->privates['.service_locator.lEubkBD'];
        }

        return $container->privates['.service_locator.lEubkBD'] = $instance;
    }
}
