<?php

namespace ContainerE5XgzCF;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4EzcLZvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4EzcLZv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4EzcLZv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'priceRepository' => ['services', 'App\\Repository\\AnalysisPriceRepository', 'getAnalysisPriceRepositoryService', true],
        ], [
            'priceRepository' => 'App\\Repository\\AnalysisPriceRepository',
        ]);
    }
}
