<?php

namespace ContainerE5XgzCF;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_T9ibSgqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.t9ibSgq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'fedaPayService' => ['privates', 'App\\Service\\FedaPayService', 'getFedaPayServiceService', true],
            'logger' => ['privates', 'monolog.logger', 'getMonolog_LoggerService', false],
        ], [
            'entityManager' => '?',
            'fedaPayService' => 'App\\Service\\FedaPayService',
            'logger' => '?',
        ]);

        if (isset($container->privates['.service_locator.t9ibSgq'])) {
            return $container->privates['.service_locator.t9ibSgq'];
        }

        return $container->privates['.service_locator.t9ibSgq'] = $instance;
    }
}
