<?php

namespace ContainerE5XgzCF;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TI3ct_PService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TI3ct.P' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TI3ct.P'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'order' => ['privates', '.errored..service_locator.TI3ct.P.App\\Entity\\Order', NULL, 'Cannot autowire service ".service_locator.TI3ct.P": it needs an instance of "App\\Entity\\Order" but this type has been excluded in "config/services.yaml".'],
            'returnOrderRepository' => ['privates', 'App\\Repository\\ReturnOrderRepository', 'getReturnOrderRepositoryService', true],
        ], [
            'order' => 'App\\Entity\\Order',
            'returnOrderRepository' => 'App\\Repository\\ReturnOrderRepository',
        ]);
    }
}
