<?php

namespace ContainerE5XgzCF;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Pv2JT1QService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Pv2JT1Q' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'promotionProduct' => ['privates', '.errored..service_locator.Pv2JT1Q.App\\Entity\\PromotionProduct', NULL, 'Cannot autowire service ".service_locator.Pv2JT1Q": it needs an instance of "App\\Entity\\PromotionProduct" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'promotionProduct' => 'App\\Entity\\PromotionProduct',
        ]);

        if (isset($container->privates['.service_locator.Pv2JT1Q'])) {
            return $container->privates['.service_locator.Pv2JT1Q'];
        }

        return $container->privates['.service_locator.Pv2JT1Q'] = $instance;
    }
}
