<?php

namespace ContainerE5XgzCF;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UMxrM5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UMxr_M5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UMxr_M5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'returnOrder' => ['privates', '.errored..service_locator.UMxr_M5.App\\Entity\\ReturnOrder', NULL, 'Cannot autowire service ".service_locator.UMxr_M5": it needs an instance of "App\\Entity\\ReturnOrder" but this type has been excluded in "config/services.yaml".'],
        ], [
            'returnOrder' => 'App\\Entity\\ReturnOrder',
        ]);
    }
}
