<?php

namespace ContainerE5XgzCF;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnalysisPrice2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.i8zDIA5.App\Entity\AnalysisPrice' shared service.
     *
     * @return \App\Entity\AnalysisPrice
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.i8zDIA5": it needs an instance of "App\\Entity\\AnalysisPrice" but this type has been excluded in "config/services.yaml".');
    }
}
