<?php

namespace ContainerE5XgzCF;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCustomerUserCheckerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Security\CustomerUserChecker' shared autowired service.
     *
     * @return \App\Security\CustomerUserChecker
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'security-core'.\DIRECTORY_SEPARATOR.'User'.\DIRECTORY_SEPARATOR.'UserCheckerInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Security'.\DIRECTORY_SEPARATOR.'CustomerUserChecker.php';

        return $container->privates['App\\Security\\CustomerUserChecker'] = new \App\Security\CustomerUserChecker(($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));
    }
}
