<?php

namespace ContainerE5XgzCF;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateMonthlySubscriptionsCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\CreateMonthlySubscriptionsCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'LazyCommand.php';

        return $container->privates['.App\\Command\\CreateMonthlySubscriptionsCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:create-monthly-subscriptions', [], 'Crée automatiquement les demandes d\'analyse pour les abonnements mensuels actifs', false, #[\Closure(name: 'App\\Command\\CreateMonthlySubscriptionsCommand')] fn (): \App\Command\CreateMonthlySubscriptionsCommand => ($container->privates['App\\Command\\CreateMonthlySubscriptionsCommand'] ?? $container->load('getCreateMonthlySubscriptionsCommandService')));
    }
}
