<?php

namespace ContainerE5XgzCF;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDashboardRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\DashboardRepository' shared autowired service.
     *
     * @return \App\Repository\DashboardRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'DashboardRepository.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Repository\\DashboardRepository'])) {
            return $container->privates['App\\Repository\\DashboardRepository'];
        }

        $instance = new \App\Repository\DashboardRepository($a);

        if (isset($container->privates['App\\Repository\\DashboardRepository'])) {
            return $container->privates['App\\Repository\\DashboardRepository'];
        }

        return $container->privates['App\\Repository\\DashboardRepository'] = $instance;
    }
}
