<?php

namespace ContainerE5XgzCF;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEnforceUserQuotasCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\EnforceUserQuotasCommand' shared autowired service.
     *
     * @return \App\Command\EnforceUserQuotasCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'EnforceUserQuotasCommand.php';

        $container->privates['App\\Command\\EnforceUserQuotasCommand'] = $instance = new \App\Command\EnforceUserQuotasCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Service\\QuotaManager'] ?? $container->load('getQuotaManagerService')));

        $instance->setName('app:enforce-user-quotas');
        $instance->setDescription('Applique les quotas d\'utilisateurs à toutes les entreprises (active/désactive selon les rôles).');

        return $instance;
    }
}
