<?php

namespace ContainerEJSh7RS;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ELJylBtService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ELJylBt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'purchase' => ['privates', '.errored..service_locator.ELJylBt.App\\Entity\\Purchase', NULL, 'Cannot autowire service ".service_locator.ELJylBt": it needs an instance of "App\\Entity\\Purchase" but this type has been excluded in "config/services.yaml".'],
        ], [
            'mailer' => '?',
            'purchase' => 'App\\Entity\\Purchase',
        ]);

        if (isset($container->privates['.service_locator.ELJylBt'])) {
            return $container->privates['.service_locator.ELJylBt'];
        }

        return $container->privates['.service_locator.ELJylBt'] = $instance;
    }
}
