<?php

namespace ContainerEJSh7RS;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPromotionProductRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\PromotionProductRepository' shared autowired service.
     *
     * @return \App\Repository\PromotionProductRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'PromotionProductRepository.php';

        return $container->privates['App\\Repository\\PromotionProductRepository'] = new \App\Repository\PromotionProductRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
