<?php

namespace ContainerEJSh7RS;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPurchaseCartServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\PurchaseCartService' shared autowired service.
     *
     * @return \App\Service\PurchaseCartService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'PurchaseCartService.php';

        return $container->privates['App\\Service\\PurchaseCartService'] = new \App\Service\PurchaseCartService(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
