<?php

namespace ContainerEJSh7RS;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSubscriptionNumberGeneratorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\SubscriptionNumberGenerator' shared autowired service.
     *
     * @return \App\Service\SubscriptionNumberGenerator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'SubscriptionNumberGenerator.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Service\\SubscriptionNumberGenerator'])) {
            return $container->privates['App\\Service\\SubscriptionNumberGenerator'];
        }

        $instance = new \App\Service\SubscriptionNumberGenerator($a, ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));

        if (isset($container->privates['App\\Service\\SubscriptionNumberGenerator'])) {
            return $container->privates['App\\Service\\SubscriptionNumberGenerator'];
        }

        return $container->privates['App\\Service\\SubscriptionNumberGenerator'] = $instance;
    }
}
