<?php

namespace ContainerMVAMfIZ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8fS6y4dService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8fS6y4d' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cartRepository' => ['services', 'App\\Repository\\CartRepository', 'getCartRepositoryService', false],
            'categoryRepository' => ['privates', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService', false],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'favoriteRepository' => ['privates', 'App\\Repository\\FavoriteRepository', 'getFavoriteRepositoryService', false],
            'productRepository' => ['privates', 'App\\Repository\\ProductRepository', 'getProductRepositoryService', true],
        ], [
            'cartRepository' => 'App\\Repository\\CartRepository',
            'categoryRepository' => 'App\\Repository\\CategoryRepository',
            'entityManager' => '?',
            'favoriteRepository' => 'App\\Repository\\FavoriteRepository',
            'productRepository' => 'App\\Repository\\ProductRepository',
        ]);

        if (isset($container->privates['.service_locator.8fS6y4d'])) {
            return $container->privates['.service_locator.8fS6y4d'];
        }

        return $container->privates['.service_locator.8fS6y4d'] = $instance;
    }
}
