<?php

namespace ContainerMVAMfIZ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GAatUmJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gAatUmJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'location' => ['privates', '.errored..service_locator.gAatUmJ.App\\Entity\\Location', NULL, 'Cannot autowire service ".service_locator.gAatUmJ": it needs an instance of "App\\Entity\\Location" but this type has been excluded in "config/services.yaml".'],
            'locationRepository' => ['privates', 'App\\Repository\\LocationRepository', 'getLocationRepositoryService', true],
        ], [
            'em' => '?',
            'location' => 'App\\Entity\\Location',
            'locationRepository' => 'App\\Repository\\LocationRepository',
        ]);

        if (isset($container->privates['.service_locator.gAatUmJ'])) {
            return $container->privates['.service_locator.gAatUmJ'];
        }

        return $container->privates['.service_locator.gAatUmJ'] = $instance;
    }
}
