<?php

namespace ContainerMVAMfIZ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCleanIncompleteCustomersCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\CleanIncompleteCustomersCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'LazyCommand.php';

        return $container->privates['.App\\Command\\CleanIncompleteCustomersCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:clean-incomplete-customers', [], 'Nettoie les clients avec inscription incomplète (soft delete après 7 jours)', false, #[\Closure(name: 'App\\Command\\CleanIncompleteCustomersCommand')] fn (): \App\Command\CleanIncompleteCustomersCommand => ($container->privates['App\\Command\\CleanIncompleteCustomersCommand'] ?? $container->load('getCleanIncompleteCustomersCommandService')));
    }
}
