<?php

namespace ContainerMVAMfIZ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReturnOrderRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\ReturnOrderRepository' shared autowired service.
     *
     * @return \App\Repository\ReturnOrderRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'ReturnOrderRepository.php';

        return $container->privates['App\\Repository\\ReturnOrderRepository'] = new \App\Repository\ReturnOrderRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
