<?php

namespace ContainerOv0BLN1;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHmaServiceProfileControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Dashboard\HmaServiceProfileController' shared autowired service.
     *
     * @return \App\Controller\Dashboard\HmaServiceProfileController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'Dashboard'.\DIRECTORY_SEPARATOR.'HmaServiceProfileController.php';

        $container->services['App\\Controller\\Dashboard\\HmaServiceProfileController'] = $instance = new \App\Controller\Dashboard\HmaServiceProfileController();

        $instance->setContainer(($container->privates['.service_locator.siKanuc'] ?? $container->load('get_ServiceLocator_SiKanucService'))->withContext('App\\Controller\\Dashboard\\HmaServiceProfileController', $container));

        return $instance;
    }
}
