<?php

namespace Container9curt44;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JO9s1qwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jO9s1qw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jO9s1qw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'movementRepository' => ['privates', 'App\\Repository\\StockMovementRepository', 'getStockMovementRepositoryService', true],
        ], [
            'movementRepository' => 'App\\Repository\\StockMovementRepository',
        ]);
    }
}
