<?php

namespace Container9curt44;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Y2AGJlhService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.y2AGJlh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.y2AGJlh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repository' => ['privates', 'App\\Repository\\SupplierCreditNoteRepository', 'getSupplierCreditNoteRepositoryService', true],
            'supplierRepository' => ['privates', 'App\\Repository\\SupplierRepository', 'getSupplierRepositoryService', true],
        ], [
            'repository' => 'App\\Repository\\SupplierCreditNoteRepository',
            'supplierRepository' => 'App\\Repository\\SupplierRepository',
        ]);
    }
}
