<?php

namespace Container9curt44;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHmaService2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.NeEnakr.App\Entity\HmaService' shared service.
     *
     * @return \App\Entity\HmaService
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.NeEnakr": it needs an instance of "App\\Entity\\HmaService" but this type has been excluded in "config/services.yaml".');
    }
}
