<?php

namespace Container9curt44;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPromotionCategoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Brzkho4.App\Entity\PromotionCategory' shared service.
     *
     * @return \App\Entity\PromotionCategory
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Brzkho4": it needs an instance of "App\\Entity\\PromotionCategory" but this type has been excluded in "config/services.yaml".');
    }
}
