<?php

namespace Container9curt44;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSupplierCreditNoteServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Service\SupplierCreditNoteService' shared autowired service.
     *
     * @return \App\Service\SupplierCreditNoteService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'SupplierCreditNoteService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'string'.\DIRECTORY_SEPARATOR.'Slugger'.\DIRECTORY_SEPARATOR.'SluggerInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'string'.\DIRECTORY_SEPARATOR.'Slugger'.\DIRECTORY_SEPARATOR.'AsciiSlugger.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->services['App\\Service\\SupplierCreditNoteService'])) {
            return $container->services['App\\Service\\SupplierCreditNoteService'];
        }
        $b = ($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService'));

        if (isset($container->services['App\\Service\\SupplierCreditNoteService'])) {
            return $container->services['App\\Service\\SupplierCreditNoteService'];
        }
        $c = ($container->privates['twig'] ?? self::getTwigService($container));

        if (isset($container->services['App\\Service\\SupplierCreditNoteService'])) {
            return $container->services['App\\Service\\SupplierCreditNoteService'];
        }

        $instance = new \App\Service\SupplierCreditNoteService($a, ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)), $b, $c, ($container->services['router'] ?? self::getRouterService($container)), ($container->privates['slugger'] ??= new \Symfony\Component\String\Slugger\AsciiSlugger('fr')), $container->getEnv('SUPPORT_EMAIL'));

        if (isset($container->services['App\\Service\\SupplierCreditNoteService'])) {
            return $container->services['App\\Service\\SupplierCreditNoteService'];
        }

        return $container->services['App\\Service\\SupplierCreditNoteService'] = $instance;
    }
}
