<?php

namespace ContainerLA30XwM;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderItemRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\OrderItemRepository' shared autowired service.
     *
     * @return \App\Repository\OrderItemRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'OrderItemRepository.php';

        return $container->privates['App\\Repository\\OrderItemRepository'] = new \App\Repository\OrderItemRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
