<?php

namespace ContainerLA30XwM;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSubscriptionPlanService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.sSPFBVg.App\Entity\SubscriptionPlan' shared service.
     *
     * @return \App\Entity\SubscriptionPlan
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.sSPFBVg": it needs an instance of "App\\Entity\\SubscriptionPlan" but this type has been excluded in "config/services.yaml".');
    }
}
