<?php

namespace ContainerYfg8NLI;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_C3hO_DcService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.c3hO.Dc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'purchaseRepository' => ['privates', 'App\\Repository\\PurchaseRepository', 'getPurchaseRepositoryService', true],
            'service' => ['services', 'App\\Service\\SupplierCreditNoteService', 'getSupplierCreditNoteServiceService', true],
            'stockBatchRepository' => ['privates', 'App\\Repository\\StockBatchRepository', 'getStockBatchRepositoryService', true],
        ], [
            'purchaseRepository' => 'App\\Repository\\PurchaseRepository',
            'service' => 'App\\Service\\SupplierCreditNoteService',
            'stockBatchRepository' => 'App\\Repository\\StockBatchRepository',
        ]);

        if (isset($container->privates['.service_locator.c3hO.Dc'])) {
            return $container->privates['.service_locator.c3hO.Dc'];
        }

        return $container->privates['.service_locator.c3hO.Dc'] = $instance;
    }
}
