<?php

namespace ContainerYfg8NLI;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnalysisPriceControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\SuperAdmin\AnalysisPriceController' shared autowired service.
     *
     * @return \App\Controller\SuperAdmin\AnalysisPriceController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\SuperAdmin\\AnalysisPriceController'] = $instance = new \App\Controller\SuperAdmin\AnalysisPriceController();

        $instance->setContainer(($container->privates['.service_locator.siKanuc'] ?? $container->load('get_ServiceLocator_SiKanucService'))->withContext('App\\Controller\\SuperAdmin\\AnalysisPriceController', $container));

        return $instance;
    }
}
