<?php

namespace ContainerYfg8NLI;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnalysisRequestTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\AnalysisRequestType' shared autowired service.
     *
     * @return \App\Form\AnalysisRequestType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\AnalysisRequestType'] = new \App\Form\AnalysisRequestType(($container->services['App\\Repository\\AnalysisPriceRepository'] ?? $container->load('getAnalysisPriceRepositoryService')));
    }
}
