<?php

namespace ContainerYfg8NLI;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoryController2Service extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Marketplace\CategoryController' shared autowired service.
     *
     * @return \App\Controller\Marketplace\CategoryController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Marketplace\\CategoryController'] = $instance = new \App\Controller\Marketplace\CategoryController();

        $instance->setContainer(($container->privates['.service_locator.siKanuc'] ?? $container->load('get_ServiceLocator_SiKanucService'))->withContext('App\\Controller\\Marketplace\\CategoryController', $container));

        return $instance;
    }
}
