<?php

namespace ContainerYfg8NLI;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCleanExpiredAnalysisCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Command\CleanExpiredAnalysisCommand' shared autowired service.
     *
     * @return \App\Command\CleanExpiredAnalysisCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\CleanExpiredAnalysisCommand'] = $instance = new \App\Command\CleanExpiredAnalysisCommand(($container->services['App\\Repository\\AnalysisRequestRepository'] ?? $container->load('getAnalysisRequestRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('app:clean-expired-analysis');
        $instance->setDescription('Nettoie les demandes d\'analyse expirées');

        return $instance;
    }
}
