<?php

namespace ContainerYfg8NLI;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCustomerChangePasswordTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\CustomerChangePasswordType' shared autowired service.
     *
     * @return \App\Form\CustomerChangePasswordType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\CustomerChangePasswordType'] = new \App\Form\CustomerChangePasswordType();
    }
}
