<?php

namespace ContainerYfg8NLI;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCartItemRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Repository\CartItemRepository' shared autowired service.
     *
     * @return \App\Repository\CartItemRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['App\\Repository\\CartItemRepository'] = new \App\Repository\CartItemRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
