<?php

namespace ContainerYfg8NLI;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEnforceQuotasCommand_LazyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.App\Command\EnforceQuotasCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\Command\\EnforceQuotasCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:enforce-quotas', [], 'Applique les quotas actuels à toutes les entreprises (désactive/réactive les entités).', false, #[\Closure(name: 'App\\Command\\EnforceQuotasCommand')] fn (): \App\Command\EnforceQuotasCommand => ($container->privates['App\\Command\\EnforceQuotasCommand'] ?? $container->load('getEnforceQuotasCommandService')));
    }
}
