<?php

namespace ContainerYfg8NLI;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFavoriteRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\FavoriteRepository' shared autowired service.
     *
     * @return \App\Repository\FavoriteRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\FavoriteRepository'] = new \App\Repository\FavoriteRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
