<?php

namespace ContainerYfg8NLI;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGenerateSalesReportCommand_LazyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.App\Command\GenerateSalesReportCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\Command\\GenerateSalesReportCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:generate-sales-report', [], 'Génère un rapport de ventes Excel (à implémenter)', false, #[\Closure(name: 'App\\Command\\GenerateSalesReportCommand')] fn (): \App\Command\GenerateSalesReportCommand => ($container->privates['App\\Command\\GenerateSalesReportCommand'] ?? $container->load('getGenerateSalesReportCommandService')));
    }
}
