<?php

namespace ContainerYfg8NLI;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHmaServiceControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\SuperAdmin\HmaServiceController' shared autowired service.
     *
     * @return \App\Controller\SuperAdmin\HmaServiceController
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));
        $b = ($container->privates['filesystem'] ??= new \Symfony\Component\Filesystem\Filesystem());

        $container->services['App\\Controller\\SuperAdmin\\HmaServiceController'] = $instance = new \App\Controller\SuperAdmin\HmaServiceController(($container->privates['App\\Repository\\HmaServiceRepository'] ?? $container->load('getHmaServiceRepositoryService')), ($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')), ($container->privates['App\\Repository\\SubscriptionRepository'] ?? $container->load('getSubscriptionRepositoryService')), $a, ($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')), ($container->privates['slugger'] ??= new \Symfony\Component\String\Slugger\AsciiSlugger('fr')), ($container->services['knp_paginator'] ?? $container->load('getKnpPaginatorService')), ($container->services['App\\Service\\EmailService'] ?? $container->load('getEmailServiceService')), $b, (\dirname(__DIR__, 4).'/public/uploads/logos'), new \App\Service\CompanyDeletionService($a, $b, ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)), (\dirname(__DIR__, 4).'/public/uploads/logos'), (\dirname(__DIR__, 4).'/public/uploads/photos'), (\dirname(__DIR__, 4).'/public/uploads/products'), (\dirname(__DIR__, 4).'/public/uploads/categories'), (\dirname(__DIR__, 4).'/public/uploads'), (\dirname(__DIR__, 4).'/public/uploads/categories_plats'), (\dirname(__DIR__, 4).'/public/uploads/images_plats'), (\dirname(__DIR__, 4).'/public/uploads/promotions'), (\dirname(__DIR__, 4).'/public/uploads/bons-commande'), (\dirname(__DIR__, 4).'/public/uploads/recus-achat'), (\dirname(__DIR__, 4).'/public/uploads/recus-abonnement'), (\dirname(__DIR__, 4).'/public/uploads/exports'), (\dirname(__DIR__, 4).'/public/uploads/exports/sales'), (\dirname(__DIR__, 4).'/public/uploads/receipts')));

        $instance->setContainer(($container->privates['.service_locator.siKanuc'] ?? $container->load('get_ServiceLocator_SiKanucService'))->withContext('App\\Controller\\SuperAdmin\\HmaServiceController', $container));

        return $instance;
    }
}
