<?php

namespace ContainerYfg8NLI;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoginSuccessHandlerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Security\LoginSuccessHandler' shared autowired service.
     *
     * @return \App\Security\LoginSuccessHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        return $container->services['App\\Security\\LoginSuccessHandler'] = new \App\Security\LoginSuccessHandler(($container->services['router'] ?? self::getRouterService($container)), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), $a, ($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')), new \App\Service\SubscriptionNumberGenerator($a, ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container))), ($container->services['App\\Service\\EmailService'] ?? $container->load('getEmailServiceService')));
    }
}
