<?php

namespace ContainerYfg8NLI;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderController2Service extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Sale\OrderController' shared autowired service.
     *
     * @return \App\Controller\Sale\OrderController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Sale\\OrderController'] = $instance = new \App\Controller\Sale\OrderController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)), ($container->services['App\\Service\\Sale\\PromotionCalculator'] ?? $container->load('getPromotionCalculatorService')));

        $instance->setContainer(($container->privates['.service_locator.siKanuc'] ?? $container->load('get_ServiceLocator_SiKanucService'))->withContext('App\\Controller\\Sale\\OrderController', $container));

        return $instance;
    }
}
