<?php

namespace ContainerYfg8NLI;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPromotionCategoryRecipeTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\PromotionCategoryRecipeType' shared autowired service.
     *
     * @return \App\Form\PromotionCategoryRecipeType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\PromotionCategoryRecipeType'] = new \App\Form\PromotionCategoryRecipeType();
    }
}
