<?php

namespace ContainerYfg8NLI;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPromotionCategoryRecipe2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.xYaj3X5.App\Entity\PromotionCategoryRecipe' shared service.
     *
     * @return \App\Entity\PromotionCategoryRecipe
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.xYaj3X5": it needs an instance of "App\\Entity\\PromotionCategoryRecipe" but this type has been excluded in "config/services.yaml".');
    }
}
