<?php

namespace ContainerYfg8NLI;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecipeItemTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\RecipeItemType' shared autowired service.
     *
     * @return \App\Form\RecipeItemType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\RecipeItemType'] = new \App\Form\RecipeItemType(($container->privates['App\\Service\\UnitConverter'] ??= new \App\Service\UnitConverter()));
    }
}
