<?php

namespace ContainerYfg8NLI;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReceiptGeneratorService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Service\Sale\ReceiptGenerator' shared autowired service.
     *
     * @return \App\Service\Sale\ReceiptGenerator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['App\\Service\\Sale\\ReceiptGenerator'] = new \App\Service\Sale\ReceiptGenerator(($container->privates['twig'] ?? $container->load('getTwigService')), new \Dompdf\Dompdf(), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)), (\dirname(__DIR__, 4).'/public/uploads/receipts'));
    }
}
