<?php

namespace ContainerYfg8NLI;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReturnServiceService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Service\Return\ReturnService' shared autowired service.
     *
     * @return \App\Service\Return\ReturnService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['App\\Service\\Return\\ReturnService'] = new \App\Service\Return\ReturnService(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\ReturnOrderRepository'] ?? $container->load('getReturnOrderRepositoryService')), ($container->privates['App\\Repository\\StockBatchRepository'] ?? $container->load('getStockBatchRepositoryService')), ($container->services['App\\Service\\StockSyncService'] ?? $container->load('getStockSyncServiceService')), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));
    }
}
