<?php

namespace ContainerYfg8NLI;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSendSubscriptionRemindersCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Command\SendSubscriptionRemindersCommand' shared autowired service.
     *
     * @return \App\Command\SendSubscriptionRemindersCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\SendSubscriptionRemindersCommand'] = $instance = new \App\Command\SendSubscriptionRemindersCommand(($container->services['App\\Repository\\AnalysisRequestRepository'] ?? $container->load('getAnalysisRequestRepositoryService')), ($container->services['App\\Service\\NotificationService'] ?? $container->load('getNotificationServiceService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('app:send-subscription-reminders');
        $instance->setDescription('Envoie des rappels pour les abonnements sur le point d\'expirer');

        return $instance;
    }
}
