<?php

namespace ContainerYfg8NLI;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSupplierCreditNoteHistoryRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\SupplierCreditNoteHistoryRepository' shared autowired service.
     *
     * @return \App\Repository\SupplierCreditNoteHistoryRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\SupplierCreditNoteHistoryRepository'] = new \App\Repository\SupplierCreditNoteHistoryRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
