<?php

namespace ContainerYfg8NLI;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSendSubscriptionRemindersCommand_LazyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.App\Command\SendSubscriptionRemindersCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\Command\\SendSubscriptionRemindersCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:send-subscription-reminders', [], 'Envoie des rappels pour les abonnements sur le point d\'expirer', false, #[\Closure(name: 'App\\Command\\SendSubscriptionRemindersCommand')] fn (): \App\Command\SendSubscriptionRemindersCommand => ($container->privates['App\\Command\\SendSubscriptionRemindersCommand'] ?? $container->load('getSendSubscriptionRemindersCommandService')));
    }
}
