<?php

namespace ContainerYfg8NLI;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSupplierCreditNoteServiceService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Service\SupplierCreditNoteService' shared autowired service.
     *
     * @return \App\Service\SupplierCreditNoteService
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->services['App\\Service\\SupplierCreditNoteService'])) {
            return $container->services['App\\Service\\SupplierCreditNoteService'];
        }
        $b = ($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService'));

        if (isset($container->services['App\\Service\\SupplierCreditNoteService'])) {
            return $container->services['App\\Service\\SupplierCreditNoteService'];
        }
        $c = ($container->privates['twig'] ?? $container->load('getTwigService'));

        if (isset($container->services['App\\Service\\SupplierCreditNoteService'])) {
            return $container->services['App\\Service\\SupplierCreditNoteService'];
        }

        $instance = new \App\Service\SupplierCreditNoteService($a, ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)), $b, $c, ($container->services['router'] ?? self::getRouterService($container)), ($container->privates['slugger'] ??= new \Symfony\Component\String\Slugger\AsciiSlugger('fr')), $container->getEnv('SUPPORT_EMAIL'));

        if (isset($container->services['App\\Service\\SupplierCreditNoteService'])) {
            return $container->services['App\\Service\\SupplierCreditNoteService'];
        }

        return $container->services['App\\Service\\SupplierCreditNoteService'] = $instance;
    }
}
