<?php

namespace ContainerYfg8NLI;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Firewall_Map_Context_CustomerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'security.firewall.map.context.customer' shared service.
     *
     * @return \Symfony\Bundle\SecurityBundle\Security\FirewallContext
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['security.firewall.map.context.customer'])) {
            return $container->privates['security.firewall.map.context.customer'];
        }
        $b = ($container->privates['security.event_dispatcher.customer'] ?? self::getSecurity_EventDispatcher_CustomerService($container));

        if (isset($container->privates['security.firewall.map.context.customer'])) {
            return $container->privates['security.firewall.map.context.customer'];
        }
        $c = ($container->privates['security.token_storage'] ?? self::getSecurity_TokenStorageService($container));
        $d = ($container->privates['security.http_utils'] ?? $container->load('getSecurity_HttpUtilsService'));

        $instance = new \Symfony\Bundle\SecurityBundle\Security\FirewallContext(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['security.channel_listener'] ?? $container->load('getSecurity_ChannelListenerService'));
            yield 1 => ($container->privates['security.context_listener.0'] ?? self::getSecurity_ContextListener_0Service($container));
            yield 2 => ($container->privates['security.firewall.authenticator.customer'] ?? $container->load('getSecurity_Firewall_Authenticator_CustomerService'));
            yield 3 => ($container->privates['security.access_listener'] ?? $container->load('getSecurity_AccessListenerService'));
        }, 4), new \Symfony\Component\Security\Http\Firewall\ExceptionListener($c, ($container->privates['security.authentication.trust_resolver'] ??= new \Symfony\Component\Security\Core\Authentication\AuthenticationTrustResolver()), $d, 'customer', new \App\Security\CustomerAuthenticator(($container->services['router'] ?? self::getRouterService($container)), $a, ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container))), NULL, NULL, ($container->privates['monolog.logger.security'] ?? self::getMonolog_Logger_SecurityService($container)), false), new \Symfony\Component\Security\Http\Firewall\LogoutListener($c, $d, $b, ['csrf_parameter' => '_csrf_token', 'csrf_token_id' => 'logout', 'logout_path' => 'marketplace_logout']), new \Symfony\Bundle\SecurityBundle\Security\FirewallConfig('customer', 'App\\Security\\CustomerUserChecker', '.security.request_matcher.tlVsCOe', true, false, 'security.user.provider.concrete.customer_provider', 'customer_context', 'App\\Security\\CustomerAuthenticator', NULL, NULL, ['form_login', 'remember_me'], NULL, ['path' => 'marketplace_logout', 'target' => 'marketplace_home', 'invalidate_session' => true, 'delete_cookies' => ['PHPSESSID' => ['path' => NULL, 'domain' => NULL, 'secure' => false, 'samesite' => NULL, 'partitioned' => false]], 'enable_csrf' => NULL, 'csrf_token_id' => 'logout', 'csrf_parameter' => '_csrf_token', 'clear_site_data' => []]));

        if (isset($container->privates['security.firewall.map.context.customer'])) {
            return $container->privates['security.firewall.map.context.customer'];
        }

        return $container->privates['security.firewall.map.context.customer'] = $instance;
    }
}
