<?php

namespace ContainerYfg8NLI;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStockMaintenanceCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Command\StockMaintenanceCommand' shared autowired service.
     *
     * @return \App\Command\StockMaintenanceCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\StockMaintenanceCommand'] = $instance = new \App\Command\StockMaintenanceCommand(($container->services['App\\Service\\StockSyncService'] ?? $container->load('getStockSyncServiceService')));

        $instance->setName('app:stock:maintenance');

        return $instance;
    }
}
