<?php

namespace ContainerYfg8NLI;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStockMovementControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Admin\StockMovementController' shared autowired service.
     *
     * @return \App\Controller\Admin\StockMovementController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Admin\\StockMovementController'] = $instance = new \App\Controller\Admin\StockMovementController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setContainer(($container->privates['.service_locator.siKanuc'] ?? $container->load('get_ServiceLocator_SiKanucService'))->withContext('App\\Controller\\Admin\\StockMovementController', $container));

        return $instance;
    }
}
