<?php

namespace ContainerYfg8NLI;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStockAdjustmentServiceService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Service\Stock\StockAdjustmentService' shared autowired service.
     *
     * @return \App\Service\Stock\StockAdjustmentService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['App\\Service\\Stock\\StockAdjustmentService'] = new \App\Service\Stock\StockAdjustmentService(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->services['App\\Service\\StockMovementService'] ?? $container->load('getStockMovementServiceService')), ($container->services['App\\Service\\NotificationService'] ?? $container->load('getNotificationServiceService')), ($container->privates['App\\Service\\FileUploader'] ?? $container->load('getFileUploaderService')), ($container->privates['App\\Repository\\StockAdjustmentRepository'] ?? $container->load('getStockAdjustmentRepositoryService')));
    }
}
