<?php

namespace ContainerYfg8NLI;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStockMovementServiceService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Service\StockMovementService' shared autowired service.
     *
     * @return \App\Service\StockMovementService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['App\\Service\\StockMovementService'] = new \App\Service\StockMovementService(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));
    }
}
