<?php

namespace ContainerYfg8NLI;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestSubscriptionEmailCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Command\TestSubscriptionEmailCommand' shared autowired service.
     *
     * @return \App\Command\TestSubscriptionEmailCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\TestSubscriptionEmailCommand'] = $instance = new \App\Command\TestSubscriptionEmailCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->services['App\\Service\\EmailService'] ?? $container->load('getEmailServiceService')));

        $instance->setName('app:test-subscription-email');
        $instance->setDescription('Test l\'envoi des emails de confirmation d\'abonnement aux utilisateurs d\'une entreprise.');

        return $instance;
    }
}
