<?php

namespace ContainerVVMsfYk;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_T_B26rYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.t.B26rY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'service' => ['services', 'App\\Service\\SupplierCreditNoteService', 'getSupplierCreditNoteServiceService', true],
            'tokenRepository' => ['privates', 'App\\Repository\\SupplierCreditNoteTokenRepository', 'getSupplierCreditNoteTokenRepositoryService', true],
        ], [
            'entityManager' => '?',
            'service' => 'App\\Service\\SupplierCreditNoteService',
            'tokenRepository' => 'App\\Repository\\SupplierCreditNoteTokenRepository',
        ]);

        if (isset($container->privates['.service_locator.t.B26rY'])) {
            return $container->privates['.service_locator.t.B26rY'];
        }

        return $container->privates['.service_locator.t.B26rY'] = $instance;
    }
}
