<?php

namespace ContainerVVMsfYk;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SSPFBVgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sSPFBVg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sSPFBVg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'plan' => ['privates', '.errored..service_locator.sSPFBVg.App\\Entity\\SubscriptionPlan', NULL, 'Cannot autowire service ".service_locator.sSPFBVg": it needs an instance of "App\\Entity\\SubscriptionPlan" but this type has been excluded in "config/services.yaml".'],
        ], [
            'plan' => 'App\\Entity\\SubscriptionPlan',
        ]);
    }
}
