<?php

namespace ContainerVVMsfYk;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPromotionCalculatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Service\Sale\PromotionCalculator' shared autowired service.
     *
     * @return \App\Service\Sale\PromotionCalculator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Sale'.\DIRECTORY_SEPARATOR.'PromotionCalculator.php';

        return $container->services['App\\Service\\Sale\\PromotionCalculator'] = new \App\Service\Sale\PromotionCalculator(($container->privates['App\\Repository\\PromotionRepository'] ?? $container->load('getPromotionRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));
    }
}
