<?php

namespace Container0A8xomv;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotificationServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Service\NotificationService' shared autowired service.
     *
     * @return \App\Service\NotificationService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'NotificationService.php';

        return $container->services['App\\Service\\NotificationService'] = new \App\Service\NotificationService(($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService')), ($container->privates['twig'] ?? self::getTwigService($container)), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)), $container->getEnv('MAILER_FROM_EMAIL'), true, $container->getEnv('APP_URL'));
    }
}
