<?php

namespace ContainerBAR6XEE;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3VaP2SMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3VaP2SM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3VaP2SM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repository' => ['privates', 'App\\Repository\\SupplierRepository', 'getSupplierRepositoryService', true],
        ], [
            'repository' => 'App\\Repository\\SupplierRepository',
        ]);
    }
}
