<?php

namespace ContainerBAR6XEE;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnalysisRequestControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\SuperAdmin\AnalysisRequestController' shared autowired service.
     *
     * @return \App\Controller\SuperAdmin\AnalysisRequestController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'SuperAdmin'.\DIRECTORY_SEPARATOR.'AnalysisRequestController.php';

        $container->services['App\\Controller\\SuperAdmin\\AnalysisRequestController'] = $instance = new \App\Controller\SuperAdmin\AnalysisRequestController(($container->services['App\\Repository\\AnalysisRequestRepository'] ?? $container->load('getAnalysisRequestRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setContainer(($container->privates['.service_locator.siKanuc'] ?? $container->load('get_ServiceLocator_SiKanucService'))->withContext('App\\Controller\\SuperAdmin\\AnalysisRequestController', $container));

        return $instance;
    }
}
