<?php

namespace ContainerBAR6XEE;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCartController2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Marketplace\CartController' shared autowired service.
     *
     * @return \App\Controller\Marketplace\CartController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'Marketplace'.\DIRECTORY_SEPARATOR.'CartController.php';

        $container->services['App\\Controller\\Marketplace\\CartController'] = $instance = new \App\Controller\Marketplace\CartController(($container->services['App\\Repository\\CartRepository'] ?? self::getCartRepositoryService($container)), ($container->privates['App\\Repository\\ProductRepository'] ?? $container->load('getProductRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->services['App\\Service\\Sale\\PromotionCalculator'] ?? $container->load('getPromotionCalculatorService')), ($container->privates['App\\Service\\FedaPayService'] ?? $container->load('getFedaPayServiceService')), ($container->services['App\\Service\\OrderService'] ?? $container->load('getOrderServiceService')), ($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService')), ($container->privates['twig'] ?? self::getTwigService($container)), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));

        $instance->setContainer(($container->privates['.service_locator.siKanuc'] ?? $container->load('get_ServiceLocator_SiKanucService'))->withContext('App\\Controller\\Marketplace\\CartController', $container));

        return $instance;
    }
}
