<?php

namespace ContainerBAR6XEE;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSaleServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Service\Sale\SaleService' shared autowired service.
     *
     * @return \App\Service\Sale\SaleService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Sale'.\DIRECTORY_SEPARATOR.'SaleService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'UnitConverter.php';

        return $container->services['App\\Service\\Sale\\SaleService'] = new \App\Service\Sale\SaleService(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->services['App\\Service\\Sale\\StockDeductionService'] ?? $container->load('getStockDeductionServiceService')), ($container->services['App\\Service\\Sale\\PromotionCalculator'] ?? $container->load('getPromotionCalculatorService')), ($container->privates['App\\Service\\UnitConverter'] ??= new \App\Service\UnitConverter()), ($container->services['App\\Service\\StockSyncService'] ?? $container->load('getStockSyncServiceService')), ($container->privates['App\\Repository\\ProductRepository'] ?? $container->load('getProductRepositoryService')), ($container->privates['App\\Repository\\RecipeRepository'] ?? $container->load('getRecipeRepositoryService')), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
