<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0A8xomv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0A8xomv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0A8xomv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0A8xomv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0A8xomv\App_KernelDevDebugContainer([
    'container.build_hash' => '0A8xomv',
    'container.build_id' => 'ee5af6b4',
    'container.build_time' => 1779329410,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container0A8xomv');
