<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGmjEZxO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGmjEZxO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGmjEZxO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGmjEZxO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGmjEZxO\App_KernelDevDebugContainer([
    'container.build_hash' => 'GmjEZxO',
    'container.build_id' => '77c5232f',
    'container.build_time' => 1787621192,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGmjEZxO');
