<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEJSh7RS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEJSh7RS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEJSh7RS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEJSh7RS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEJSh7RS\App_KernelDevDebugContainer([
    'container.build_hash' => 'EJSh7RS',
    'container.build_id' => 'd818a32d',
    'container.build_time' => 1773018311,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEJSh7RS');
