<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AnalysisRequest extends \App\Entity\AnalysisRequest implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'amount' => [parent::class, 'amount', null, 16],
        "\0".parent::class."\0".'company' => [parent::class, 'company', null, 16],
        "\0".parent::class."\0".'created_at' => [parent::class, 'created_at', null, 16],
        "\0".parent::class."\0".'expires_at' => [parent::class, 'expires_at', null, 16],
        "\0".parent::class."\0".'export_file_path' => [parent::class, 'export_file_path', null, 16],
        "\0".parent::class."\0".'exported_at' => [parent::class, 'exported_at', null, 16],
        "\0".parent::class."\0".'finalReportFilename' => [parent::class, 'finalReportFilename', null, 16],
        "\0".parent::class."\0".'finalReportPath' => [parent::class, 'finalReportPath', null, 16],
        "\0".parent::class."\0".'finalReportType' => [parent::class, 'finalReportType', null, 16],
        "\0".parent::class."\0".'finalReportUploadedAt' => [parent::class, 'finalReportUploadedAt', null, 16],
        "\0".parent::class."\0".'finalReportUploadedBy' => [parent::class, 'finalReportUploadedBy', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'notes' => [parent::class, 'notes', null, 16],
        "\0".parent::class."\0".'paid_at' => [parent::class, 'paid_at', null, 16],
        "\0".parent::class."\0".'payment_transaction_id' => [parent::class, 'payment_transaction_id', null, 16],
        "\0".parent::class."\0".'period_end' => [parent::class, 'period_end', null, 16],
        "\0".parent::class."\0".'period_start' => [parent::class, 'period_start', null, 16],
        "\0".parent::class."\0".'rawExportPath' => [parent::class, 'rawExportPath', null, 16],
        "\0".parent::class."\0".'rawExportedAt' => [parent::class, 'rawExportedAt', null, 16],
        "\0".parent::class."\0".'request_number' => [parent::class, 'request_number', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null, 16],
        "\0".parent::class."\0".'updated_at' => [parent::class, 'updated_at', null, 16],
        'amount' => [parent::class, 'amount', null, 16],
        'company' => [parent::class, 'company', null, 16],
        'created_at' => [parent::class, 'created_at', null, 16],
        'expires_at' => [parent::class, 'expires_at', null, 16],
        'export_file_path' => [parent::class, 'export_file_path', null, 16],
        'exported_at' => [parent::class, 'exported_at', null, 16],
        'finalReportFilename' => [parent::class, 'finalReportFilename', null, 16],
        'finalReportPath' => [parent::class, 'finalReportPath', null, 16],
        'finalReportType' => [parent::class, 'finalReportType', null, 16],
        'finalReportUploadedAt' => [parent::class, 'finalReportUploadedAt', null, 16],
        'finalReportUploadedBy' => [parent::class, 'finalReportUploadedBy', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'notes' => [parent::class, 'notes', null, 16],
        'paid_at' => [parent::class, 'paid_at', null, 16],
        'payment_transaction_id' => [parent::class, 'payment_transaction_id', null, 16],
        'period_end' => [parent::class, 'period_end', null, 16],
        'period_start' => [parent::class, 'period_start', null, 16],
        'rawExportPath' => [parent::class, 'rawExportPath', null, 16],
        'rawExportedAt' => [parent::class, 'rawExportedAt', null, 16],
        'request_number' => [parent::class, 'request_number', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'type' => [parent::class, 'type', null, 16],
        'updated_at' => [parent::class, 'updated_at', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
