<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AnalysisPayment extends \App\Entity\AnalysisPayment implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'amount' => [parent::class, 'amount', null, 16],
        "\0".parent::class."\0".'analysis_request' => [parent::class, 'analysis_request', null, 16],
        "\0".parent::class."\0".'created_at' => [parent::class, 'created_at', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'paid_at' => [parent::class, 'paid_at', null, 16],
        "\0".parent::class."\0".'payment_data' => [parent::class, 'payment_data', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'transaction_id' => [parent::class, 'transaction_id', null, 16],
        'amount' => [parent::class, 'amount', null, 16],
        'analysis_request' => [parent::class, 'analysis_request', null, 16],
        'created_at' => [parent::class, 'created_at', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'paid_at' => [parent::class, 'paid_at', null, 16],
        'payment_data' => [parent::class, 'payment_data', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'transaction_id' => [parent::class, 'transaction_id', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
