<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class StockTransfer extends \App\Entity\StockTransfer implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'created_at' => [parent::class, 'created_at', null, 16],
        "\0".parent::class."\0".'created_by' => [parent::class, 'created_by', null, 16],
        "\0".parent::class."\0".'destination_location' => [parent::class, 'destination_location', null, 16],
        "\0".parent::class."\0".'hma_service' => [parent::class, 'hma_service', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'quantity' => [parent::class, 'quantity', null, 16],
        "\0".parent::class."\0".'reason' => [parent::class, 'reason', null, 16],
        "\0".parent::class."\0".'received_at' => [parent::class, 'received_at', null, 16],
        "\0".parent::class."\0".'received_by' => [parent::class, 'received_by', null, 16],
        "\0".parent::class."\0".'source_location' => [parent::class, 'source_location', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'stock_batch' => [parent::class, 'stock_batch', null, 16],
        "\0".parent::class."\0".'transfer_number' => [parent::class, 'transfer_number', null, 16],
        "\0".parent::class."\0".'updated_at' => [parent::class, 'updated_at', null, 16],
        'created_at' => [parent::class, 'created_at', null, 16],
        'created_by' => [parent::class, 'created_by', null, 16],
        'destination_location' => [parent::class, 'destination_location', null, 16],
        'hma_service' => [parent::class, 'hma_service', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'quantity' => [parent::class, 'quantity', null, 16],
        'reason' => [parent::class, 'reason', null, 16],
        'received_at' => [parent::class, 'received_at', null, 16],
        'received_by' => [parent::class, 'received_by', null, 16],
        'source_location' => [parent::class, 'source_location', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'stock_batch' => [parent::class, 'stock_batch', null, 16],
        'transfer_number' => [parent::class, 'transfer_number', null, 16],
        'updated_at' => [parent::class, 'updated_at', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
