<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ReturnItem extends \App\Entity\ReturnItem implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'item_id' => [parent::class, 'item_id', null, 16],
        "\0".parent::class."\0".'item_type' => [parent::class, 'item_type', null, 16],
        "\0".parent::class."\0".'original_order_item' => [parent::class, 'original_order_item', null, 16],
        "\0".parent::class."\0".'product_name' => [parent::class, 'product_name', null, 16],
        "\0".parent::class."\0".'promotion_id' => [parent::class, 'promotion_id', null, 16],
        "\0".parent::class."\0".'promotion_name' => [parent::class, 'promotion_name', null, 16],
        "\0".parent::class."\0".'quantity_returned' => [parent::class, 'quantity_returned', null, 16],
        "\0".parent::class."\0".'refund_amount' => [parent::class, 'refund_amount', null, 16],
        "\0".parent::class."\0".'return_order' => [parent::class, 'return_order', null, 16],
        "\0".parent::class."\0".'total_refund' => [parent::class, 'total_refund', null, 16],
        "\0".parent::class."\0".'unit_price_at_sale' => [parent::class, 'unit_price_at_sale', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'item_id' => [parent::class, 'item_id', null, 16],
        'item_type' => [parent::class, 'item_type', null, 16],
        'original_order_item' => [parent::class, 'original_order_item', null, 16],
        'product_name' => [parent::class, 'product_name', null, 16],
        'promotion_id' => [parent::class, 'promotion_id', null, 16],
        'promotion_name' => [parent::class, 'promotion_name', null, 16],
        'quantity_returned' => [parent::class, 'quantity_returned', null, 16],
        'refund_amount' => [parent::class, 'refund_amount', null, 16],
        'return_order' => [parent::class, 'return_order', null, 16],
        'total_refund' => [parent::class, 'total_refund', null, 16],
        'unit_price_at_sale' => [parent::class, 'unit_price_at_sale', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
