<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Inventory extends \App\Entity\Inventory implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'created_at' => [parent::class, 'created_at', null, 16],
        "\0".parent::class."\0".'created_by' => [parent::class, 'created_by', null, 16],
        "\0".parent::class."\0".'hma_service' => [parent::class, 'hma_service', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'inventory_date' => [parent::class, 'inventory_date', null, 16],
        "\0".parent::class."\0".'inventory_number' => [parent::class, 'inventory_number', null, 16],
        "\0".parent::class."\0".'items' => [parent::class, 'items', null, 16],
        "\0".parent::class."\0".'location' => [parent::class, 'location', null, 16],
        "\0".parent::class."\0".'notes' => [parent::class, 'notes', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'updated_at' => [parent::class, 'updated_at', null, 16],
        "\0".parent::class."\0".'validated_at' => [parent::class, 'validated_at', null, 16],
        "\0".parent::class."\0".'validated_by' => [parent::class, 'validated_by', null, 16],
        'created_at' => [parent::class, 'created_at', null, 16],
        'created_by' => [parent::class, 'created_by', null, 16],
        'hma_service' => [parent::class, 'hma_service', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'inventory_date' => [parent::class, 'inventory_date', null, 16],
        'inventory_number' => [parent::class, 'inventory_number', null, 16],
        'items' => [parent::class, 'items', null, 16],
        'location' => [parent::class, 'location', null, 16],
        'notes' => [parent::class, 'notes', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'updated_at' => [parent::class, 'updated_at', null, 16],
        'validated_at' => [parent::class, 'validated_at', null, 16],
        'validated_by' => [parent::class, 'validated_by', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
