<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Invoice extends \App\Entity\Invoice implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'amountFcfa' => [parent::class, 'amountFcfa', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'dueDate' => [parent::class, 'dueDate', null, 16],
        "\0".parent::class."\0".'hma_service' => [parent::class, 'hma_service', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'invoiceNumber' => [parent::class, 'invoiceNumber', null, 16],
        "\0".parent::class."\0".'paidAt' => [parent::class, 'paidAt', null, 16],
        "\0".parent::class."\0".'pdfPath' => [parent::class, 'pdfPath', null, 16],
        "\0".parent::class."\0".'periodEnd' => [parent::class, 'periodEnd', null, 16],
        "\0".parent::class."\0".'periodStart' => [parent::class, 'periodStart', null, 16],
        "\0".parent::class."\0".'sentAt' => [parent::class, 'sentAt', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'subscription' => [parent::class, 'subscription', null, 16],
        'amountFcfa' => [parent::class, 'amountFcfa', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'dueDate' => [parent::class, 'dueDate', null, 16],
        'hma_service' => [parent::class, 'hma_service', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'invoiceNumber' => [parent::class, 'invoiceNumber', null, 16],
        'paidAt' => [parent::class, 'paidAt', null, 16],
        'pdfPath' => [parent::class, 'pdfPath', null, 16],
        'periodEnd' => [parent::class, 'periodEnd', null, 16],
        'periodStart' => [parent::class, 'periodStart', null, 16],
        'sentAt' => [parent::class, 'sentAt', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'subscription' => [parent::class, 'subscription', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
