<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class StockMovement extends \App\Entity\StockMovement implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'created_at' => [parent::class, 'created_at', null, 16],
        "\0".parent::class."\0".'hma_service' => [parent::class, 'hma_service', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'movement_type' => [parent::class, 'movement_type', null, 16],
        "\0".parent::class."\0".'notes' => [parent::class, 'notes', null, 16],
        "\0".parent::class."\0".'product' => [parent::class, 'product', null, 16],
        "\0".parent::class."\0".'purchase_item' => [parent::class, 'purchase_item', null, 16],
        "\0".parent::class."\0".'quantity' => [parent::class, 'quantity', null, 16],
        "\0".parent::class."\0".'reference_id' => [parent::class, 'reference_id', null, 16],
        "\0".parent::class."\0".'stock_batch' => [parent::class, 'stock_batch', null, 16],
        "\0".parent::class."\0".'unit_price' => [parent::class, 'unit_price', null, 16],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null, 16],
        'created_at' => [parent::class, 'created_at', null, 16],
        'hma_service' => [parent::class, 'hma_service', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'movement_type' => [parent::class, 'movement_type', null, 16],
        'notes' => [parent::class, 'notes', null, 16],
        'product' => [parent::class, 'product', null, 16],
        'purchase_item' => [parent::class, 'purchase_item', null, 16],
        'quantity' => [parent::class, 'quantity', null, 16],
        'reference_id' => [parent::class, 'reference_id', null, 16],
        'stock_batch' => [parent::class, 'stock_batch', null, 16],
        'unit_price' => [parent::class, 'unit_price', null, 16],
        'user' => [parent::class, 'user', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
