<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Payment extends \App\Entity\Payment implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'amount' => [parent::class, 'amount', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'hma_service' => [parent::class, 'hma_service', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'invoiceNumber' => [parent::class, 'invoiceNumber', null, 16],
        "\0".parent::class."\0".'notes' => [parent::class, 'notes', null, 16],
        "\0".parent::class."\0".'paymentDate' => [parent::class, 'paymentDate', null, 16],
        "\0".parent::class."\0".'paymentMethod' => [parent::class, 'paymentMethod', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'subscription' => [parent::class, 'subscription', null, 16],
        "\0".parent::class."\0".'subscriptionNumber' => [parent::class, 'subscriptionNumber', null, 16],
        "\0".parent::class."\0".'transactionId' => [parent::class, 'transactionId', null, 16],
        'amount' => [parent::class, 'amount', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'hma_service' => [parent::class, 'hma_service', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'invoiceNumber' => [parent::class, 'invoiceNumber', null, 16],
        'notes' => [parent::class, 'notes', null, 16],
        'paymentDate' => [parent::class, 'paymentDate', null, 16],
        'paymentMethod' => [parent::class, 'paymentMethod', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'subscription' => [parent::class, 'subscription', null, 16],
        'subscriptionNumber' => [parent::class, 'subscriptionNumber', null, 16],
        'transactionId' => [parent::class, 'transactionId', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
