<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ReturnOrder extends \App\Entity\ReturnOrder implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'approved_at' => [parent::class, 'approved_at', null, 16],
        "\0".parent::class."\0".'approved_by' => [parent::class, 'approved_by', null, 16],
        "\0".parent::class."\0".'completed_at' => [parent::class, 'completed_at', null, 16],
        "\0".parent::class."\0".'completed_by' => [parent::class, 'completed_by', null, 16],
        "\0".parent::class."\0".'created_at' => [parent::class, 'created_at', null, 16],
        "\0".parent::class."\0".'customer_name' => [parent::class, 'customer_name', null, 16],
        "\0".parent::class."\0".'customer_phone' => [parent::class, 'customer_phone', null, 16],
        "\0".parent::class."\0".'hma_service' => [parent::class, 'hma_service', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'notes' => [parent::class, 'notes', null, 16],
        "\0".parent::class."\0".'order_number' => [parent::class, 'order_number', null, 16],
        "\0".parent::class."\0".'original_order' => [parent::class, 'original_order', null, 16],
        "\0".parent::class."\0".'reason' => [parent::class, 'reason', null, 16],
        "\0".parent::class."\0".'reason_notes' => [parent::class, 'reason_notes', null, 16],
        "\0".parent::class."\0".'refund_method' => [parent::class, 'refund_method', null, 16],
        "\0".parent::class."\0".'returnItems' => [parent::class, 'returnItems', null, 16],
        "\0".parent::class."\0".'return_date' => [parent::class, 'return_date', null, 16],
        "\0".parent::class."\0".'return_number' => [parent::class, 'return_number', null, 16],
        "\0".parent::class."\0".'returned_by' => [parent::class, 'returned_by', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'total_refund_amount' => [parent::class, 'total_refund_amount', null, 16],
        "\0".parent::class."\0".'updated_at' => [parent::class, 'updated_at', null, 16],
        'approved_at' => [parent::class, 'approved_at', null, 16],
        'approved_by' => [parent::class, 'approved_by', null, 16],
        'completed_at' => [parent::class, 'completed_at', null, 16],
        'completed_by' => [parent::class, 'completed_by', null, 16],
        'created_at' => [parent::class, 'created_at', null, 16],
        'customer_name' => [parent::class, 'customer_name', null, 16],
        'customer_phone' => [parent::class, 'customer_phone', null, 16],
        'hma_service' => [parent::class, 'hma_service', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'notes' => [parent::class, 'notes', null, 16],
        'order_number' => [parent::class, 'order_number', null, 16],
        'original_order' => [parent::class, 'original_order', null, 16],
        'reason' => [parent::class, 'reason', null, 16],
        'reason_notes' => [parent::class, 'reason_notes', null, 16],
        'refund_method' => [parent::class, 'refund_method', null, 16],
        'returnItems' => [parent::class, 'returnItems', null, 16],
        'return_date' => [parent::class, 'return_date', null, 16],
        'return_number' => [parent::class, 'return_number', null, 16],
        'returned_by' => [parent::class, 'returned_by', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'total_refund_amount' => [parent::class, 'total_refund_amount', null, 16],
        'updated_at' => [parent::class, 'updated_at', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
