<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class InventoryItem extends \App\Entity\InventoryItem implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'actual_quantity' => [parent::class, 'actual_quantity', null, 16],
        "\0".parent::class."\0".'counted_at' => [parent::class, 'counted_at', null, 16],
        "\0".parent::class."\0".'counted_by' => [parent::class, 'counted_by', null, 16],
        "\0".parent::class."\0".'difference' => [parent::class, 'difference', null, 16],
        "\0".parent::class."\0".'expected_quantity' => [parent::class, 'expected_quantity', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'inventory' => [parent::class, 'inventory', null, 16],
        "\0".parent::class."\0".'location' => [parent::class, 'location', null, 16],
        "\0".parent::class."\0".'notes' => [parent::class, 'notes', null, 16],
        "\0".parent::class."\0".'product' => [parent::class, 'product', null, 16],
        "\0".parent::class."\0".'stock_batch' => [parent::class, 'stock_batch', null, 16],
        'actual_quantity' => [parent::class, 'actual_quantity', null, 16],
        'counted_at' => [parent::class, 'counted_at', null, 16],
        'counted_by' => [parent::class, 'counted_by', null, 16],
        'difference' => [parent::class, 'difference', null, 16],
        'expected_quantity' => [parent::class, 'expected_quantity', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'inventory' => [parent::class, 'inventory', null, 16],
        'location' => [parent::class, 'location', null, 16],
        'notes' => [parent::class, 'notes', null, 16],
        'product' => [parent::class, 'product', null, 16],
        'stock_batch' => [parent::class, 'stock_batch', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
