<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class SupplierCreditNoteHistory extends \App\Entity\SupplierCreditNoteHistory implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'action' => [parent::class, 'action', null, 16],
        "\0".parent::class."\0".'creditNote' => [parent::class, 'creditNote', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'new_value' => [parent::class, 'new_value', null, 16],
        "\0".parent::class."\0".'notes' => [parent::class, 'notes', null, 16],
        "\0".parent::class."\0".'old_value' => [parent::class, 'old_value', null, 16],
        "\0".parent::class."\0".'performed_at' => [parent::class, 'performed_at', null, 16],
        "\0".parent::class."\0".'performed_by' => [parent::class, 'performed_by', null, 16],
        "\0".parent::class."\0".'performed_by_name' => [parent::class, 'performed_by_name', null, 16],
        'action' => [parent::class, 'action', null, 16],
        'creditNote' => [parent::class, 'creditNote', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'new_value' => [parent::class, 'new_value', null, 16],
        'notes' => [parent::class, 'notes', null, 16],
        'old_value' => [parent::class, 'old_value', null, 16],
        'performed_at' => [parent::class, 'performed_at', null, 16],
        'performed_by' => [parent::class, 'performed_by', null, 16],
        'performed_by_name' => [parent::class, 'performed_by_name', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
