<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class SupplierCreditNoteToken extends \App\Entity\SupplierCreditNoteToken implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'creditNote' => [parent::class, 'creditNote', null, 16],
        "\0".parent::class."\0".'expires_at' => [parent::class, 'expires_at', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'ip_address' => [parent::class, 'ip_address', null, 16],
        "\0".parent::class."\0".'token' => [parent::class, 'token', null, 16],
        "\0".parent::class."\0".'used_at' => [parent::class, 'used_at', null, 16],
        "\0".parent::class."\0".'user_agent' => [parent::class, 'user_agent', null, 16],
        'creditNote' => [parent::class, 'creditNote', null, 16],
        'expires_at' => [parent::class, 'expires_at', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'ip_address' => [parent::class, 'ip_address', null, 16],
        'token' => [parent::class, 'token', null, 16],
        'used_at' => [parent::class, 'used_at', null, 16],
        'user_agent' => [parent::class, 'user_agent', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
